import { ArrowRight, ArrowUpRight, ChevronDown, FileText, Target } from 'lucide-react';
import { MARKETER_BASIS_LABELS, MARKETER_STAGE_LABELS, METRIC_KINDS } from '../../utils/marketerEvidence';
import { MARKETER_WORK_PRODUCTS } from '../../utils/marketerWorkProducts';
const text = (value, fallback = '미기록') => typeof value === 'string' && value.trim() ? value : fallback;
function Field({ label, value }) { return <div className="mk-field"><small>{label}</small><p className={!value ? 'is-empty' : ''}>{text(value)}</p></div>; }
function Source({ row }) {
  const located = ['source_excerpt', 'self_report'].includes(row.basis);
  return <footer className="mk-source">{row.userEdited && <small>직접 수정한 정리 · 원문과 의미 대조 필요</small>}{row.ownership && <p>내 기여 · {row.ownership}</p>}{located ? <details><summary><FileText size={12} />{row.sourceName || MARKETER_BASIS_LABELS[row.basis]}<ChevronDown size={12} /></summary><blockquote>{row.quote}</blockquote><small>{MARKETER_BASIS_LABELS[row.basis]} · {row.location || '추출 본문'}</small></details> : <small>{MARKETER_BASIS_LABELS[row.basis] || '원문 확인 필요'}</small>}</footer>;
}
function WorkBlock({ group, rows }) {
  if (!rows.length) return null;
  const spec = MARKETER_WORK_PRODUCTS.find(entry => entry.key === group);
  return <section className={`mk-work-block mk-work-${group}`} aria-label={spec.label}><header><h4>{spec.label}</h4><span>{rows.length}개 기록</span></header>
    {group === 'creatives' ? <div className="mk-creative-grid">{rows.map((row, i) => <article key={i}><div className="mk-creative-top"><span>CREATIVE {String(i + 1).padStart(2, '0')}</span><b>{text(row.format, '형식 미기록')}</b></div><div className="mk-copy-sheet"><small>{text(row.variant, '소재')}</small><h5>{text(row.hook, '후킹 문구 미기록')}</h5><p>{text(row.message, '본문 미기록')}</p>{row.cta && <span className="mk-copy-cta">{row.cta}<ArrowUpRight size={13} /></span>}</div><Field label="왜 이 표현이었나" value={row.rationale} /><Field label="관찰한 반응 · 승자 추정 없음" value={row.observation} /><Source row={row} /></article>)}</div>
    : group === 'channels' ? <div className="mk-channel-table" role="region" aria-label="채널 운영표" tabIndex={0}><table><thead><tr><th>채널 / 고객</th><th>역할 · 선택 근거</th><th>예산 · 기간</th><th>다음 접점</th></tr></thead><tbody>{rows.map((row, i) => <tr key={i}><th scope="row"><b>{text(row.channel)}</b><small className="ma-stage-label">{MARKETER_STAGE_LABELS[row.stage] || '단계 확인 필요'}</small><p>{text(row.audience)}</p><Source row={row} /></th><td><Field label="역할" value={row.purpose} /><p>{text(row.rationale)}</p></td><td><Field label="예산" value={row.budget} /><Field label="기간" value={row.period} /></td><td><Field label="다음 접점" value={row.handoff} /></td></tr>)}</tbody></table></div>
    : group === 'crm' ? <div className="mk-crm-rules">{rows.map((row, i) => <article key={i}><header><span>RULE {String(i + 1).padStart(2, '0')}</span><b>{MARKETER_STAGE_LABELS[row.stage] || '단계 확인 필요'}</b></header><div className="mk-crm-path"><Field label="WHO · 대상 조건" value={row.segment} /><ArrowRight size={16} /><Field label="WHEN · 진입 트리거" value={row.trigger} /><ArrowRight size={16} /><Field label="SEND · 발송 시점" value={row.timing} /></div><div className="mk-crm-message"><small>{row.stage === 'planned' ? '발송 예정 메시지' : row.stage === 'unknown' ? '메시지 문안 · 발송 여부 미확인' : '고객 메시지'}</small><p>{text(row.message)}</p></div><div className="mk-field-pair"><Field label="종료 · 제외 조건" value={row.exit} /><Field label="빈도 · 고객 보호" value={row.guardrail} /></div><Source row={row} /></article>)}</div>
    : group === 'experiments' ? <div className="mk-experiment-log">{rows.map((row, i) => <article key={i}><header><span>TEST {String(i + 1).padStart(2, '0')}</span><b>{MARKETER_STAGE_LABELS[row.stage] || '단계 확인 필요'}</b></header><h5>{text(row.hypothesis)}</h5><div className="mk-field-pair"><Field label="바꾼 변수" value={row.variable} /><Field label="통제한 조건" value={row.control} /><Field label="테스트 방법" value={row.test} /><Field label="사전 성공 기준" value={row.successCriteria} /></div><div className="mk-test-verdict"><Field label="실제 관찰" value={row.observation} /><ArrowRight size={17} /><Field label="관찰 후 결정" value={row.decision} /></div>{row.limitation && <p className="mk-caution">검증 한계 · {row.limitation}</p>}<Source row={row} /></article>)}</div>
    : group === 'positioning' ? <div className="mk-message-house">{rows.map((row, i) => <article key={i}><span>{text(row.audience, '대상 미기록')}</span><h5>{text(row.promise, '전달 약속 미기록')}</h5><div className="mk-field-pair"><Field label="믿을 이유" value={row.proof} /><Field label="다른 선택지와의 차이" value={row.difference} /></div><Field label="표현과 톤" value={row.tone} /><Source row={row} /></article>)}</div>
    : group === 'contentSystem' ? <div className="ma-editorial-plan">{rows.map((row, i) => <article key={i}><header><span>CONTENT {String(i + 1).padStart(2, '0')}</span><b>{MARKETER_STAGE_LABELS[row.stage] || '단계 확인 필요'}</b></header><h5>{row.pillar}</h5><Field label="독자가 이 콘텐츠를 찾는 이유" value={row.intent} /><div className="ma-distribution-plan"><Field label="만드는 형식" value={row.format} /><Field label="배포하는 곳" value={row.distribution} /><Field label="발행 주기" value={row.cadence} /></div>{row.reuse && <Field label="한 콘텐츠를 확장한 방식" value={row.reuse} />}<Source row={row} /></article>)}</div>
    : group === 'measurement' ? <div className="ma-measurement-spec">{rows.map((row, i) => <article key={i}><header><span>MEASUREMENT</span><b>{row.sourceSystem || '데이터 출처 미기록'}</b></header><h5>{row.event}</h5><Field label="무엇을 성과로 집계했는가 · 이벤트와 분모" value={row.definition} /><div className="mk-field-pair"><Field label="관찰·기여 기간" value={row.window} /><Field label="어떤 기여를 인정했는가" value={row.attribution} /></div>{row.limitation && <p className="ma-caution">이 수치로 설명할 수 없는 것 · {row.limitation}</p>}<Source row={row} /></article>)}</div>
    : group === 'optimization' ? <div className="ma-optimization-log">{rows.map((row, i) => <article key={i}><header><span>ITERATION {String(i + 1).padStart(2, '0')}</span><b>{MARKETER_STAGE_LABELS[row.stage] || '단계 확인 필요'}</b></header><ol>{[['signal', '발견한 신호'], ['diagnosis', '원인에 대한 판단'], ['change', '수정한 선택'], ['observation', '수정 후 관찰'], ['next', '다음 실행']].filter(([field]) => row[field]).map(([field, label]) => <li key={field}><small>{label}</small><p>{row[field]}</p></li>)}</ol><Source row={row} /></article>)}</div>
    : group === 'operations' ? <div className="ma-production-scope">{rows.map((row, i) => <article key={i}><header><span>PRODUCTION</span><b>{MARKETER_STAGE_LABELS[row.stage] || '단계 확인 필요'}</b></header><h5>{row.deliverable}</h5><div className="mk-field-pair"><Field label="함께 작업한 사람" value={row.stakeholder} /><Field label="지켜야 했던 제약" value={row.constraint} /></div><div className="ma-my-action"><Field label="내가 직접 해결·조율한 일" value={row.myAction} />{row.agreement && <Field label="합의한 실행 범위" value={row.agreement} />}</div><Source row={row} /></article>)}</div>
    : <div className="mk-work-cards">{rows.map((row, i) => <article key={i}><h5>{text(row[spec.fields[0][0]])}</h5><div className="mk-field-pair">{spec.fields.slice(1).map(([field, label]) => <Field key={field} label={label} value={row[field]} />)}</div><Source row={row} /></article>)}</div>}
  </section>;
}
function Metrics({ item }) {
  return <section className="mk-results" aria-label="성과와 제작량 구분"><header><Target size={16} /><h4>무엇이 달라졌는가</h4><small>성과 · 산출량 · 정성 반응을 구분합니다</small></header>{item.metrics.length ? <div className="mk-metric-grid">{item.metrics.map((row, i) => <article key={i}><small>{METRIC_KINDS[row.kind]}{row.channel && ' · ' + row.channel}</small><h5>{row.name}</h5><div className="mk-metric-values"><div><small>기준값</small><b>{text(row.baseline, '—')}</b></div><ArrowRight size={17} /><div><small>실제 관찰값</small><strong>{text(row.actual, '미확인')}</strong></div></div><p>목표 {text(row.target, '미기록')}</p>{row.reportedValue && <p className="mk-caution">기존 수치 · 원문 대조 전: {row.reportedValue}</p>}<p>{[row.period, row.population, row.method].filter(Boolean).join(' · ') || '기간·표본·측정 정의 미기록'}</p><Source row={row} /></article>)}</div> : <p className="mk-empty-note">실측 지표가 없는 경험입니다. 소재·운영 설계와 관찰한 정성 피드백으로 설명할 수 있습니다.</p>}{item.attributionLimit && <p className="mk-caution">성과 해석 한계 · {item.attributionLimit}</p>}</section>;
}

export { Field, Source, WorkBlock, Metrics };
