import { ArrowRight } from 'lucide-react';
import { PM_WORK_PRODUCTS } from '../../utils/pmWorkProducts';
import { PM_STAGE_LABELS } from '../../utils/pmEvidence';
const text = (value, fallback = '미기록') => typeof value === 'string' && value.trim() ? value : fallback;
function Mini({ label, value }) { return <div className="pm-board-mini"><small>{label}</small><p className={!value ? 'is-empty' : ''}>{text(value)}</p></div>; }
function Evidence({ row, Source }) { return <footer>{row.userEdited && <small>직접 수정한 정리 · 원문과 의미 대조 필요</small>}<span>{PM_STAGE_LABELS[row.stage]}{row.basis === 'unlocated' ? ' · 원문 확인 필요' : ''}</span><Source record={row} /></footer>; }
function Block({ group, rows, Source }) {
  if (!rows.length) return null;
  const title = PM_WORK_PRODUCTS.find(item => item.key === group)?.label;
  return <section className={`pm-board-block pm-block-${group}`} aria-label={title}><header><h4>{title}</h4><span>{String(rows.length).padStart(2, '0')}</span></header>
    {group === 'serviceBlueprint' ? <><p className="pm-board-note">같은 단계의 고객·접점·운영·시스템을 함께 읽습니다. 연결선은 업무 순서이며 자동화나 출시 완료를 의미하지 않습니다.</p><div className="pm-blueprint" role="region" aria-label="서비스 블루프린트 표" tabIndex={0}><table><thead><tr><th scope="col">업무 레이어</th>{rows.map((row, i) => <th scope="col" key={i}><small>STEP {i + 1}</small>{row.step}</th>)}</tr></thead><tbody>{[['customerAction', '고객 행동'], ['frontstage', '화면 · 접점'], ['backstage', '운영 · 파트너'], ['system', '시스템'], ['exception', '예외 · 실패']].map(([field, label]) => <tr key={field}><th scope="row">{label}</th>{rows.map((row, i) => <td key={i}>{text(row[field], '—')}</td>)}</tr>)}<tr><th scope="row">근거</th>{rows.map((row, i) => <td key={i}><Evidence row={row} Source={Source} /></td>)}</tr></tbody></table></div></>
    : group === 'alternatives' ? <div className="pm-decision-matrix" role="region" aria-label="대안 비교표" tabIndex={0}><table><thead><tr><th>대안 / 결정</th><th>판단 기준</th><th>얻는 것 · 감수한 제약</th><th>선택·제외 이유</th></tr></thead><tbody>{rows.map((row, i) => <tr key={i} className={row.disposition === '채택' ? 'is-chosen' : ''}><th scope="row"><span className="pm-board-state">{text(row.disposition)}</span><b>{text(row.option)}</b><Evidence row={row} Source={Source} /></th><td>{text(row.criterion)}</td><td>{text(row.tradeoff)}</td><td>{text(row.reason)}</td></tr>)}</tbody></table></div>
    : group === 'metricLinks' ? <div className="pm-metric-network">{rows.map((row, i) => <article key={i}><div className="pm-metric-edge"><div><small>바꾸려는 행동 · 선행지표</small><h5>{text(row.driver)}</h5></div><ArrowRight size={22} /><div><small>연결된 결과지표</small><h5>{text(row.outcome)}</h5></div></div><p className="pm-edge-reason">{text(row.relationship, '인과관계 미확인')}</p><div className="pm-board-pair"><Mini label="측정 설계" value={row.measurement} /><Mini label="함께 지켜야 할 지표" value={row.guardrail} /></div><Evidence row={row} Source={Source} /></article>)}</div>
    : group === 'research' ? <div className="pm-insight-map">{rows.map((row, i) => <article key={i}><span className="pm-board-state">{text(row.segment, '대상 미기록')}</span><div className="pm-insight-path"><Mini label="01 관찰한 사실" value={row.observation} /><Mini label="02 해석 · 인사이트" value={row.insight} /><Mini label="03 선택한 제품 기회" value={row.opportunity} /></div>{row.limitation && <p className="pm-board-caution">반례 · 한계 / {row.limitation}</p>}<Evidence row={row} Source={Source} /></article>)}</div>
    : group === 'businessModel' ? <div className="pm-value-exchanges">{rows.map((row, i) => <article key={i}><div className="pm-value-map"><Mini label="사용하는 사람" value={row.customer} /><div className="pm-value-center"><span>VALUE</span><h5>{text(row.value)}</h5></div><Mini label="비용을 부담하는 사람" value={row.payer} /></div><div className="pm-board-pair"><Mini label="사업에 돌아오는 가치" value={row.revenue} /><Mini label="필요한 비용 · 운영 부담" value={row.cost} /></div>{row.tradeoff && <p className="pm-board-caution">균형을 잡은 지점 / {row.tradeoff}</p>}<Evidence row={row} Source={Source} /></article>)}</div>
    : group === 'requirements' ? <div className="pm-policy-console">{rows.map((row, i) => <article className="pm-spec" key={i}><header><code>POLICY / {String(i + 1).padStart(2, '0')}</code><h5>{text(row.requirement)}</h5></header><div className="pm-policy-rule"><small>RULE · 조건과 처리</small><p>{text(row.rule)}</p></div><div className="pm-policy-accept"><small>ACCEPTANCE · 완료를 확인하는 방법</small><p>{text(row.acceptance)}</p></div><Mini label="내 책임 범위" value={row.owner} /><Evidence row={row} Source={Source} /></article>)}</div>
    : group === 'journey' ? <ol className="pm-service-flow">{rows.map((row, i) => <li key={i}><span>{String(i + 1).padStart(2, '0')}</span><article><h5>{text(row.step)}</h5><small>{text(row.actor, '행동 주체 미기록')}</small><div className="pm-board-pair"><Mini label="기존" value={row.before} /><Mini label="설계 · 변경" value={row.after} /></div>{row.exception && <p className="pm-board-caution">예외 / {row.exception}</p>}<Evidence row={row} Source={Source} /></article></li>)}</ol>
    : group === 'experiments' ? <div className="pm-experiment-lab">{rows.map((row, i) => <article key={i}><header><span>EXP {String(i + 1).padStart(2, '0')}</span><b>{PM_STAGE_LABELS[row.stage]}</b></header><h5>{text(row.hypothesis)}</h5><div className="pm-board-pair"><Mini label="검증 방법 · 대상" value={row.method} /><Mini label="사전에 정한 성공 기준" value={row.successCriteria} /></div><div className="pm-experiment-verdict"><Mini label="실제 관찰" value={row.observation} /><Mini label="그 결과 내린 결정" value={row.decision} /></div><Evidence row={row} Source={Source} /></article>)}</div>
    : group === 'releases' ? <ol className="pm-release-track">{rows.map((row, i) => <li key={i}><span>{String(i + 1).padStart(2, '0')}</span><article><header><h5>{text(row.milestone)}</h5><b>{text(row.status, PM_STAGE_LABELS[row.stage])}</b></header><Mini label="포함 · 제외한 범위" value={row.scope} /><div className="pm-board-pair"><Mini label="먼저 풀어야 할 의존성" value={row.dependency} /><Mini label="출시 판단 기준" value={row.gate} /></div><Evidence row={row} Source={Source} /></article></li>)}</ol>
    : group === 'collaboration' ? <div className="pm-alignment-map">{rows.map((row, i) => <article key={i}><header><span>{text(row.stakeholder)}</span><small>ALIGNMENT</small></header><div className="pm-insight-path"><Mini label="충돌 · 의존성" value={row.disagreement} /><Mini label="내가 한 조율" value={row.myAction} /><Mini label="도달한 합의" value={row.agreement} /></div><Evidence row={row} Source={Source} /></article>)}</div>
    : group === 'risks' ? <div className="pm-risk-register">{rows.map((row, i) => <article key={i}><header><span>RISK {i + 1}</span><h5>{text(row.risk)}</h5></header><div className="pm-board-pair"><Mini label="발생 조건" value={row.trigger} /><Mini label="대응 · 안전장치" value={row.mitigation} /><Mini label="책임 범위" value={row.owner} /><Mini label="실제 확인 결과" value={row.result} /></div><Evidence row={row} Source={Source} /></article>)}</div>
    : group === 'troubleshooting' ? <div className="pm-learning-log">{rows.map((row, i) => <article key={i}><h5>{text(row.issue)}</h5><div className="pm-insight-path"><Mini label="원인" value={row.cause} /><Mini label="수정" value={row.change} /><Mini label="관찰 결과" value={row.result} /></div><p className="pm-board-learning">다음 판단에 남긴 것 / {text(row.learning)}</p><Evidence row={row} Source={Source} /></article>)}</div>
    : <div className="pm-problem-brief">{rows.map((row, i) => <article key={i}><span>{text(row.user, '대상 미기록')}</span><h5>{text(row.problem)}</h5><Mini label="사용 맥락" value={row.context} /><div className="pm-board-pair"><Mini label="관찰한 신호" value={row.signal} /><Mini label="지금 해결할 사업적 이유" value={row.businessReason} /></div><Evidence row={row} Source={Source} /></article>)}</div>}
  </section>;
}

function Outcome({ item, Source }) {
  return <div className="pm-outcome-dashboard">{item.metrics.map((metric, i) => <article className="pm-proof-metric" key={i}><header><h4>{metric.name}</h4><span>{metric.actual ? '관찰 기록' : '측정 설계'}</span></header><div className="pm-outcome-values"><div><small>기준값</small><b>{text(metric.baseline)}</b></div><ArrowRight size={20} /><div className="pm-proof-actual"><small>실제 관찰값</small><strong>{text(metric.actual, '미측정·미기록')}</strong></div><div><small>목표</small><b>{text(metric.target)}</b></div></div><div className="pm-board-pair"><Mini label="기간 · 대상" value={[metric.period, metric.population].filter(Boolean).join(' · ')} /><Mini label="측정 정의" value={metric.method} /></div><Source record={metric} /><p className="pm-board-note">{metric.limitation || '전후 변화만으로 이 결정의 인과효과를 단정하지 않습니다.'}</p></article>)}</div>;
}


export { Block, Outcome };
