import { ArrowUpRight, ChevronRight } from 'lucide-react';
import { pmProofMap, marketingProofMap } from '../../utils/roleProofMap';
import './RoleProofMaps.css';

const text = (value, fallback = '기록 없음') => value || fallback;
function Proof({ row }) {
  if (!row) return null;
  return <small className="rpm-proof">{row.userEdited ? '직접 작성·수정 · ' : ''}{row.basis === 'source_excerpt' ? row.sourceName || '자료 원문 대조' : row.basis === 'self_report' ? '본인 진술' : '원문 확인 필요'}{row.stage === 'planned' ? ' · 계획' : ''}</small>;
}
function Open({ to, children, navigate }) { return <button type="button" className="rpm-open print:hidden" onClick={() => navigate(to)}>{children || '기록 확인'}<ArrowUpRight size={13} /></button>; }
function Missing({ children }) { return <p className="rpm-missing">{children}</p>; }

export function PmDecisionCanvas({ item, navigate }) {
  const p = pmProofMap(item);
  return <section className="rpm-map rpm-product" aria-label="PM 핵심 경험 지도"><header className="rpm-map-title"><div><span>PRODUCT DECISION MAP</span><h3>내가 바꾼 제품의 구조와 판단</h3></div><p>대표 발췌 · 상세 기록과 원문은 각 영역에서 확인</p></header>
    <div className="rpm-product-top"><section className="rpm-discovery"><header><span>01 / 문제 선택</span><Open to="context" navigate={navigate} /></header>{p.problem ? <><h4>{p.problem.problem || p.problem.observation || p.problem.claim}</h4><p>{p.problem.businessReason || p.problem.insight || p.problem.signal}</p><Proof row={p.problem} /></> : <Missing>사용자 발화·VOC·행동 기록에서 해결할 문제와 그 이유를 정리하세요.</Missing>}
      <div className="rpm-options"><small>선택과 포기</small>{p.alternatives.length ? p.alternatives.map((row, i) => <div key={i}><b data-chosen={row.disposition === '채택'}>{text(row.disposition, '미확인')}</b><span>{row.option}<small>{row.reason || row.tradeoff}</small></span></div>) : <Missing>실제 비교한 대안과 제외한 이유를 연결하세요. 임의의 우선순위 점수는 만들지 않습니다.</Missing>}<Open to="decisions" navigate={navigate}>대안 비교 근거</Open></div>
    </section><section className="rpm-service"><header><span>02 / 서비스 구조</span><Open to="flow" navigate={navigate}>동작 · 예외 상세</Open></header>{p.flow.length ? <ol>{p.flow.map((row, i) => <li key={i}><code>{String(i + 1).padStart(2, '0')}</code><div><h4>{row.step}</h4><p>{row.frontstage || row.after || row.customerAction}</p>{row.exception && <small>예외 / {row.exception}</small>}</div>{i < p.flow.length - 1 && <ChevronRight size={14} />}</li>)}</ol> : <Missing>화면 흐름·운영 시나리오가 연결되면 실제 순서대로 구조를 표시합니다.</Missing>}
      <div className="rpm-policy"><header><span>POLICY / 인수 조건</span><Open to="spec" navigate={navigate} /></header>{p.policy ? <><h4>{p.policy.requirement}</h4><dl><div><dt>동작 규칙</dt><dd>{text(p.policy.rule)}</dd></div><div><dt>완료를 확인하는 기준</dt><dd>{text(p.policy.acceptance)}</dd></div></dl><Proof row={p.policy} /></> : <Missing>권한·조건·예외와 테스트 가능한 완료 기준을 정리하세요.</Missing>}</div>
    </section></div>
    <div className="rpm-product-bottom"><section><header><span>03 / 실행 책임</span><Open to="release" navigate={navigate} /></header>{p.execution ? <><h4>{p.execution.stakeholder || p.execution.milestone || '내가 책임진 실행'}</h4><p>{p.execution.myAction || p.execution.scope || p.execution.claim}</p>{(p.execution.agreement || p.execution.gate) && <p className="rpm-result">합의·출시 기준 / {p.execution.agreement || p.execution.gate}</p>}<Proof row={p.execution} /></> : <Missing>협업 중 내 판단·합의·책임 범위를 연결하세요.</Missing>}</section>
      <section><header><span>04 / 검증과 변화</span><Open to="validation" navigate={navigate} /></header>{p.metrics.length > 0 && <div className="rpm-numbers">{p.metrics.map((row, i) => <div key={i}><small>{row.name}</small><b>{row.actual || '미측정·미기록'}</b><span>기준 {row.baseline || '미기록'} · 목표 {row.target || '미기록'}</span><Proof row={row} /></div>)}</div>}{p.validation ? <><p>{p.validation.hypothesis || p.validation.claim}</p><p className="rpm-result">{p.validation.observation || '실제 관찰 결과는 아직 기록되지 않았습니다.'}</p><Proof row={p.validation} /></> : !p.metrics.length && <Missing>가설·관찰·실측을 구분해서 연결하세요. 출시 전 경험도 설계와 학습으로 설명할 수 있습니다.</Missing>}{p.learning && <div className="rpm-learning"><small>판단을 바꾼 지점</small><p>{p.learning.change || p.learning.claim}</p><Proof row={p.learning} /></div>}</section></div>
  </section>;
}

export function MarketingCampaignCanvas({ item, navigate }) {
  const p = marketingProofMap(item);
  return <section className="rpm-map rpm-marketing" aria-label="마케터 핵심 경험 지도"><header className="rpm-map-title"><div><span>CAMPAIGN WORK MAP</span><h3>고객에게 닿은 전략과 실행</h3></div><p>대표 발췌 · 채널 간 인과나 소재별 성과를 추정하지 않습니다</p></header>
    <div className="rpm-audience-band"><div><span>선택한 고객</span><h4>{p.audience?.segment || p.audience?.claim || '타깃 근거 미기록'}</h4>{p.audience?.barrier && <p>행동 장벽 / {p.audience.barrier}</p>}<Proof row={p.audience} /></div><div><span>전달할 약속</span><h4>{p.promise?.promise || p.audience?.choice || '메시지 전략 미기록'}</h4>{p.promise?.proof && <p>믿을 이유 / {p.promise.proof}</p>}<Proof row={p.promise} /><Open to="strategy" navigate={navigate}>타깃 · 포지셔닝 근거</Open></div></div>
    <div className="rpm-campaign-work"><section className="rpm-message-desk"><header><span>CREATIVE / 메시지 설계</span><Open to="creative" navigate={navigate}>모든 소재 · 원본</Open></header>{p.creatives.length ? <div className="rpm-copy-samples">{p.creatives.slice(0, 2).map((row, i) => <article key={i}><small>{row.variant || row.format || '소재 문안'}</small><h4>{text(row.hook, '후킹 문구 미기록')}</h4><p>{row.message}</p>{row.cta && <b>CTA / {row.cta}</b>}<div><small>선택 이유</small><p>{text(row.rationale)}</p></div><Proof row={row} /></article>)}</div> : <Missing>직접 만든 카피·광고·콘텐츠를 연결하세요. 가상의 시안이나 A/B 승자를 만들지 않습니다.</Missing>}<small className="rpm-caption">추출 문안이며 원본 디자인이 아닙니다. 전체 캠페인 성과를 개별 소재 성과로 귀속하지 않습니다.</small></section>
      <section className="rpm-media-desk"><header><span>MEDIA / 채널의 역할</span><Open to="activation" navigate={navigate} /></header>{p.channels.length ? <div className="rpm-channel-ledger">{p.channels.map((row, i) => <article key={i}><h4>{row.channel}</h4><p>{row.purpose}</p><dl><div><dt>예산</dt><dd>{text(row.budget)}</dd></div><div><dt>기간</dt><dd>{text(row.period)}</dd></div><div><dt>다음 접점</dt><dd>{text(row.handoff)}</dd></div></dl><Proof row={row} /></article>)}</div> : <Missing>접점 선택의 이유·배분·다음 행동을 연결하세요. 채널이 없으면 퍼널을 만들지 않습니다.</Missing>}</section></div>
    {(p.content || p.crm) && <div className="rpm-lifecycle"><header><span>지속 운영 / 콘텐츠 · CRM</span><Open to="activation" navigate={navigate} /></header>{p.content && <article><small>콘텐츠 운영 구조</small><h4>{p.content.pillar}</h4><p>{[p.content.format, p.content.distribution, p.content.cadence].filter(Boolean).join(' · ')}</p>{p.content.reuse && <p>재활용 / {p.content.reuse}</p>}<Proof row={p.content} /></article>}{p.crm && <article><small>{p.crm.stage === 'planned' ? '발송 계획' : 'CRM 조건 기록'}</small><h4>{p.crm.segment}</h4><dl><div><dt>진입 조건</dt><dd>{p.crm.trigger}</dd></div><div><dt>메시지</dt><dd>{text(p.crm.message)}</dd></div><div><dt>종료 · 빈도 보호</dt><dd>{[p.crm.exit, p.crm.guardrail].filter(Boolean).join(' · ') || '미기록'}</dd></div></dl><Proof row={p.crm} /></article>}</div>}
    <div className="rpm-iteration"><header><span>LEARNING / 성과를 해석한 방식</span><Open to="learning" navigate={navigate}>검증 · 개선 근거</Open></header><div>{p.optimization ? <article><small>관찰 뒤 바꾼 선택</small><h4>{p.optimization.change || p.optimization.decision || p.optimization.claim}</h4><p>{p.optimization.diagnosis || p.optimization.next}</p><Proof row={p.optimization} /></article> : <Missing>타깃·소재·예산을 왜 바꾸거나 유지했는지 정리하세요.</Missing>}{p.measurement ? <article><small>측정의 기준과 한계</small><h4>{p.measurement.event}</h4><p>{p.measurement.definition}</p><p>{p.measurement.limitation || p.measurement.attribution}</p><Proof row={p.measurement} /></article> : <Missing>지표의 분모·측정 기간·기여 범위를 연결하세요. 기록이 없으면 인과효과를 단정하지 않습니다.</Missing>}</div></div>
  </section>;
}
