const DEV_ACCENT = '#002F6C';

const devArtifact = ({ repo, mine, total, rank, file, problem, solution, impact, diff, outcomes }) => ({
  jobCategory: 'dev',
  product: { problem, solution, outcomes },
  githubStats: {
    repoName: repo,
    myCommits: mine,
    totalCommits: total,
    contributionPct: Math.round((mine / total) * 100),
    rank,
    contributorCount: 4,
    commitTypes: [
      { type: 'feat', count: Math.max(6, Math.round(mine * 0.46)) },
      { type: 'fix', count: Math.max(4, Math.round(mine * 0.28)) },
      { type: 'test/docs', count: Math.max(3, Math.round(mine * 0.18)) },
    ],
    languages: [{ name: 'TypeScript', pct: 78 }, { name: 'JavaScript', pct: 14 }, { name: 'CSS', pct: 8 }],
  },
  gitAnalysis: {
    repoName: repo,
    experiences: [{
      project_name: repo,
      core_tech_stack: 'React, TypeScript, Testing',
      problem_definition: problem,
      action_and_solution: solution,
      core_impact: impact,
      code_snippets: [{ file, code: diff, why: `${impact}를 만든 핵심 변경입니다. 삭제·추가 라인을 함께 보여 주어 실제 기여 범위를 확인할 수 있습니다.` }],
      learning: '성능·접근성·운영 품질은 구현 이후 점검 항목이 아니라 설계 단계의 완료 조건으로 관리해야 합니다.',
    }],
  },
});

const pmArtifact = ({ problem, solution, uvp, customers, early, metrics, roadmap, hypothesis, decision }) => ({
  jobCategory: 'pm',
  product: { problem, solution },
  leanCanvas: {
    uvp,
    customers,
    earlyAdopters: early,
    existingAlternatives: '수기 기록\n여러 도구를 오가는 기존 업무\n담당자의 경험에 의존한 처리',
  },
  portfolioVisuals: {
    kpis: metrics.map(metric => ({ label: metric.label, value: metric.value, target: metric.target })),
    goals: metrics.slice(0, 2).map(metric => ({ label: metric.label, actual: metric.value, target: metric.target, achieved: true })),
    timeline: roadmap.map((item, index) => ({ label: item.label, start: index + 1, span: 1, desc: item.value })),
  },
  pmTimeline: {
    description: '리서치 근거가 정책과 화면, 검증 지표까지 이어지는 실행 로드맵입니다.',
    items: roadmap.map((item, index) => ({
      phase: item.phase,
      label: item.label,
      value: item.value,
      color: index === roadmap.length - 1 ? '#04bd5e' : DEV_ACCENT,
    })),
  },
  pmHypotheses: [{ hypothesis, kpi: metrics[0].label, target: metrics[0].target, achievement: metrics[0].value, note: decision }],
  keyExperiences: [{
    title: roadmap[2]?.label || '핵심 기능 검증',
    metricLabel: metrics[0].label,
    beforeMetric: metrics[0].before,
    afterMetric: metrics[0].value,
    jobData: { hypothesis, decision, alternatives: '전체 개편 대신 핵심 병목만 먼저 검증', impact: metrics[0].value, effort: '2주 MVP' },
  }],
  jobSpecific: { strategy: decision },
});

const marketerArtifact = ({ problem, target, strategy, execution, result, insight, metrics, funnel }) => ({
  jobCategory: 'marketer',
  portfolioVisuals: {
    kpis: metrics.map(metric => ({ label: metric.name, value: metric.value, target: metric.target || '' })),
    funnel: funnel.map(stage => ({ label: stage.label, value: stage.value, unit: stage.unit || '명' })),
    compare: metrics.filter(metric => metric.before).slice(0, 2).map(metric => ({ label: metric.name, before: metric.before, after: metric.value })),
  },
  marketerKit: {
    positioning: `${target}의 행동 맥락을 기준으로 메시지와 채널을 연결한 캠페인`,
    funnel: { problem, goal: result, target, strategy, execution, result, insight },
    kpis: metrics.map(metric => ({ name: metric.name, value: metric.value, status: metric.status || `목표 ${metric.target || '달성'}` })),
    resumeBullets: [
      `${strategy}를 실행해 ${result}`,
      `${execution} 과정에서 KPI 대시보드를 운영하고 다음 실험 기준을 문서화했습니다.`,
    ],
    positioningReport: {
      strengths: ['가설·소재·성과를 한 화면에서 연결', '허수 지표보다 다음 행동에 가까운 KPI를 관리'],
      weaknesses: ['장기 LTV와 증분 효과는 후속 검증 필요'],
      recommendation: insight,
    },
  },
});

const EXAMPLE_ARTIFACTS = {
  '모아 — 취향 기반 모임 탐색 서비스': devArtifact({
    repo: 'team-moa/web', mine: 86, total: 191, rank: 1, file: 'src/features/search/useSearchFilters.ts',
    problem: '필터 변경마다 목록 상태가 초기화되고 중복 요청이 발생해 검색 이탈이 높았습니다.',
    solution: 'URL을 단일 상태 원천으로 삼고 debounce와 쿼리 캐시를 결합해 뒤로가기·공유·재진입 흐름을 안정화했습니다.',
    impact: '첫 결과 2.8초 → 1.4초, 상세 진입률 22% → 31%',
    outcomes: [{ label: '검색 결과 첫 표시', value: '2.8초 → 1.4초' }, { label: '검색 이탈률', value: '-18%' }],
    diff: "-const [filters, setFilters] = useState(defaultFilters);\n+const filters = parseSearchParams(searchParams);\n+const query = useQuery({ queryKey: ['groups', filters], staleTime: 30_000 });\n+const updateFilter = debounce(next => setSearchParams(serialize(next)), 300);",
  }),
  '페이퍼리스 — 전자계약 대시보드': devArtifact({
    repo: 'doyoon/paperless', mine: 142, total: 142, rank: 1, file: 'src/components/ContractTable.tsx',
    problem: '1,000건 계약 목록의 전체 DOM 렌더링과 분산된 폼 검증 때문에 화면 지연과 오류 누락이 발생했습니다.',
    solution: '행 가상화와 Zod 스키마 기반 조건부 검증을 도입하고 키보드 포커스 순서를 함께 테스트했습니다.',
    impact: '1,000행 렌더링 1.9초 → 0.6초, Lighthouse 접근성 100점',
    outcomes: [{ label: '1,000행 렌더링', value: '0.6초' }, { label: '유틸 테스트 커버리지', value: '86%' }],
    diff: "-contracts.map(contract => <ContractRow contract={contract} />)\n+const rowVirtualizer = useVirtualizer({ count: contracts.length, estimateSize: () => 52 });\n+rowVirtualizer.getVirtualItems().map(row => (\n+  <ContractRow contract={contracts[row.index]} style={{ transform: `translateY(${row.start}px)` }} />\n+));",
  }),
  '캠퍼스픽 웹 성능 개선': devArtifact({
    repo: 'campuspick/frontend', mine: 34, total: 112, rank: 2, file: 'src/pages/Home.tsx',
    problem: '히어로 이미지와 초기 진입에 불필요한 모달 코드가 모바일 LCP와 번들 크기를 키웠습니다.',
    solution: '반응형 이미지와 lazy import를 적용하고 Lighthouse CI 성능 예산을 PR 차단 조건으로 만들었습니다.',
    impact: '모바일 LCP 3.6초 → 2.1초, 초기 JavaScript 31% 감소',
    outcomes: [{ label: '모바일 LCP', value: '3.6초 → 2.1초' }, { label: '초기 JS 번들', value: '-31%' }],
    diff: "-import EventModal from './EventModal';\n+const EventModal = lazy(() => import('./EventModal'));\n+<picture>\n+  <source srcSet={heroAvif} type=\"image/avif\" />\n+  <img src={heroWebp} fetchPriority=\"high\" alt=\"오늘의 캠퍼스 소식\" />\n+</picture>",
  }),
  '오픈UI 접근성 개선 기여': devArtifact({
    repo: 'open-ui/learning-components', mine: 27, total: 96, rank: 3, file: 'packages/dialog/useFocusTrap.ts',
    problem: '모달의 포커스가 배경으로 빠지고 닫은 뒤 트리거로 복귀하지 않아 키보드 사용자가 흐름을 잃었습니다.',
    solution: '공통 포커스 트랩 훅과 복귀 로직을 분리하고 Storybook interaction·axe 검사를 CI에 추가했습니다.',
    impact: '키보드 핵심 오류 14건 → 2건, 접근성 PR 7건 릴리스 반영',
    outcomes: [{ label: '반영된 PR', value: '7건' }, { label: '키보드 오류', value: '14건 → 2건' }],
    diff: "+const previousFocus = document.activeElement as HTMLElement;\n+dialog.addEventListener('keydown', loopFocus);\n+return () => {\n+  dialog.removeEventListener('keydown', loopFocus);\n+  previousFocus?.focus();\n+};",
  }),
  'DevLink — 개발 동아리 운영 플랫폼': devArtifact({
    repo: 'devlink/community', mine: 71, total: 174, rank: 1, file: 'functions/src/reminders.ts',
    problem: '행사 알림이 수동으로 발송돼 누락됐고 중복 실행 시 같은 알림이 여러 번 전송될 위험이 있었습니다.',
    solution: '예약 작업에 멱등 키와 재시도 큐를 적용하고 실패 이벤트를 Sentry 운영 대시보드에 연결했습니다.',
    impact: '주간 운영 3시간 → 50분, 행사 노쇼율 23% → 9%',
    outcomes: [{ label: '주간 운영 시간', value: '50분' }, { label: '행사 노쇼율', value: '9%' }],
    diff: "+const idempotencyKey = `${eventId}:${reminderType}`;\n+if (await reminderSent(idempotencyKey)) return;\n+await sendReminder(memberIds, template);\n+await markReminderSent(idempotencyKey);",
  }),

  '끼니로그 — 1인 가구 식비 관리': pmArtifact({
    problem: '품목을 직접 입력하는 피로 때문에 1인 가구 사용자가 가계부를 2주 안에 포기했습니다.',
    solution: '영수증 촬영 → OCR 검수 → 식사 유형 선택의 30초 기록 흐름과 실패 복구 정책을 설계했습니다.',
    uvp: '사진 한 장으로 끝나는 식비 기록\nOCR가 틀려도 막히지 않는 복구 경험', customers: '식비를 관리하고 싶지만 수기 입력은 포기한 1인 가구', early: '주 3회 이상 카드·영수증으로 식비를 쓰는 20–30대',
    metrics: [{ label: '기록 완료율', before: '55%', value: '71%', target: '65%' }, { label: '4주 리텐션', value: '27%', target: '25%' }, { label: 'OCR 단계 이탈', before: '34%', value: '18%', target: '20%' }],
    roadmap: [{ phase: 'DISCOVER', label: '문제 발견', value: '인터뷰 15명·리뷰 240건 분류' }, { phase: 'DEFINE', label: 'MVP 범위', value: '촬영·검수·주간 요약에 집중' }, { phase: 'BUILD', label: '정책·화면 설계', value: 'PRD 24쪽·와이어프레임 32화면' }, { phase: 'VALIDATE', label: '베타 검증', value: '48명·4주 리텐션 측정' }],
    hypothesis: 'OCR 결과를 단계별로 복구할 수 있으면 기록 완료율이 65%를 넘을 것이다.', decision: '챌린지·통계 기능을 제외하고 기록 성공 경험을 MVP의 최우선 범위로 결정했습니다.',
  }),
  '클래스온 수강 이탈 개선': pmArtifact({
    problem: '신규 수강생의 46%가 결제 후 24시간 안에 첫 강의를 시작하지 않았습니다.',
    solution: '결제 완료 직후 3단계 체크리스트와 바로 학습 CTA를 노출하는 2주 MVP를 설계했습니다.',
    uvp: '결제 후 무엇을 해야 할지 10초 안에 이해하는 온보딩', customers: '온라인 클래스를 처음 결제한 모바일 수강생', early: '결제 후 준비물·학습 위치를 찾지 못한 신규 수강생',
    metrics: [{ label: '첫 강의 시작률', before: '54%', value: '66%', target: '62%' }, { label: '실험 표본', value: '1,842명', target: '1,500명' }, { label: '환불률', value: '변화 없음', target: '비열등' }],
    roadmap: [{ phase: 'W1', label: '퍼널·VOC 진단', value: 'GA4 퍼널·VOC 312건 태깅' }, { phase: 'W2', label: '우선순위 결정', value: '모바일 진입·준비물 병목 선정' }, { phase: 'W3', label: '2주 MVP 설계', value: '체크리스트·CTA·14개 이벤트 명세' }, { phase: 'W4', label: 'A/B 테스트', value: '1,842명 대상 성과·가드레일 검증' }],
    hypothesis: '결제 직후 다음 행동을 체크리스트로 제시하면 첫 강의 시작률이 8%p 이상 오른다.', decision: '전면 재설계 대신 개발 2주 안에 검증 가능한 결제 완료 화면만 변경했습니다.',
  }),
  '우리동네 안심귀가 서비스': pmArtifact({
    problem: '야간 귀가자는 최단 경로 외에 CCTV·가로등·24시간 매장을 여러 앱에서 따로 확인했습니다.',
    solution: '안전 요소의 근거가 보이는 경로 점수와 지인 공유 흐름을 프로토타입으로 검증했습니다.',
    uvp: '빠른 길보다 안심할 근거가 보이는 귀가 경로', customers: '야간에 혼자 귀가하는 20대 여성', early: '대학가·역세권에서 주 2회 이상 늦게 귀가하는 사용자',
    metrics: [{ label: '경로 선택 성공률', before: '58%', value: '87%', target: '80%' }, { label: '심층 인터뷰', value: '12명', target: '10명' }, { label: '현장 관찰', value: '3회', target: '3회' }],
    roadmap: [{ phase: 'DISCOVER', label: '현장 리서치', value: '인터뷰 12명·현장 관찰 3회' }, { phase: 'MODEL', label: '안심 점수 정의', value: 'CCTV·조도·유동 인구 데이터 요구사항' }, { phase: 'PROTOTYPE', label: '경로·공유 설계', value: '와이어프레임 28화면' }, { phase: 'TEST', label: 'Maze 검증', value: '성공률 58% → 87%' }],
    hypothesis: '숫자 점수보다 안전 요소의 근거를 펼쳐 보이면 경로 선택 성공률이 높아진다.', decision: '안전 점수 단일 숫자를 폐기하고 요소별 근거와 데이터 갱신 시점을 함께 노출했습니다.',
  }),
  '캠퍼스 셔틀 예약 경험 개선': pmArtifact({
    problem: '노선명과 실제 정류장 표기가 달라 좌석 선택 이후 탑승 장소 단계에서 이탈이 집중됐습니다.',
    solution: '시간 → 정류장 사진 → 좌석 → QR 안내 순으로 예약 흐름과 17개 예외 정책을 재설계했습니다.',
    uvp: '처음 타도 1분 안에 끝나는 셔틀 예약', customers: '교내 셔틀을 처음 이용하거나 익숙하지 않은 학생', early: '등교 시간대 모바일로 급하게 예약하는 학생',
    metrics: [{ label: '예약 완료율', before: '63%', value: '81%', target: '75%' }, { label: '평균 예약 시간', before: '134초', value: '58초', target: '60초' }, { label: '일 문의', before: '26건', value: '11건', target: '15건' }],
    roadmap: [{ phase: 'DATA', label: '퍼널 분석', value: '예약 로그 8,420건·문의 186건' }, { phase: 'FIELD', label: '현장 관찰', value: '정류장 표기·탑승 행동 4회 관찰' }, { phase: 'POLICY', label: '예외 정책 설계', value: '취소·대기·QR 등 17개 상태 정의' }, { phase: 'PILOT', label: '시범 운영', value: '32명 테스트 후 문의 감소 확인' }],
    hypothesis: '노선을 시간 중심으로 먼저 고르면 예약 완료율이 75% 이상으로 오른다.', decision: '노선 코드보다 사용자가 실제로 보는 출발 시간과 정류장 사진을 정보 위계의 첫 순서로 변경했습니다.',
  }),
  '동네상점 재고관리 운영 정책': pmArtifact({
    problem: '입고 취소·단위 변환·동시 수정에서 재고 불일치가 반복되고 상담 처리 기준도 달랐습니다.',
    solution: 'VOC 분류, 셀프 진단, 보정 권한, 에스컬레이션 기준을 하나의 운영 정책으로 연결했습니다.',
    uvp: '오류를 스스로 진단하고 고위험 건만 빠르게 연결하는 재고 운영', customers: '재고 담당자가 따로 없는 소상공인 점주', early: '여러 기기에서 입출고를 동시에 처리하는 상점',
    metrics: [{ label: '재고 불일치 신고율', before: '18%', value: '7%', target: '10%' }, { label: '첫 응답 시간', before: '9.4시간', value: '3.1시간', target: '4시간' }, { label: '분석 VOC', value: '684건', target: '600건' }],
    roadmap: [{ phase: 'AUDIT', label: 'VOC 분류', value: '문의 684건·행동 로그 연결' }, { phase: 'RULE', label: '운영 정책', value: '복원·충돌·보정 권한 기준 정의' }, { phase: 'SELF-SERVE', label: '셀프 진단', value: '매크로 23개·도움말 14편' }, { phase: 'MONITOR', label: '운영 대시보드', value: '주간 위험 지표·월간 개선 리포트' }],
    hypothesis: '반복 문의를 셀프 진단으로 전환하면 첫 응답 시간이 4시간 아래로 줄어든다.', decision: '빈도보다 데이터 복구 필요성과 매출 영향을 기준으로 에스컬레이션 우선순위를 정했습니다.',
  }),

  '모닝빈 신제품 런칭 캠페인': marketerArtifact({
    problem: '기존 고객이 40대에 집중돼 저당 신제품의 핵심 타깃 유입이 부족했습니다.', target: '출근 전 간편함과 포만감을 원하는 25–34세 직장인',
    strategy: '저칼로리 대신 바쁜 아침의 든든한 3분 메시지로 6개 카피를 A/B 테스트', execution: 'Meta 소재 24종·크리에이터 18명·랜딩 메시지를 동일한 사용 장면으로 연결',
    result: '첫 달 매출 4,860만원, ROAS 405%, 신규 고객 68%를 달성했습니다.', insight: '할인보다 실제 사용 장면을 먼저 보여 준 후기형 세로 영상이 CPA를 31% 낮췄습니다.',
    metrics: [{ name: 'ROAS', value: '405%', target: '300%', status: '목표 대비 135%' }, { name: '첫 달 매출', value: '4,860만원', target: '3,500만원' }, { name: '신규 고객', value: '68%', target: '55%' }, { name: '랜딩 CVR', value: '3.1%', status: '후기형 소재 최고' }],
    funnel: [{ label: '노출', value: 1240000 }, { label: '랜딩', value: 41200 }, { label: '장바구니', value: 3860 }, { label: '구매', value: 1277 }],
  }),
  '제로웨이스트 위크 CRM 캠페인': marketerArtifact({
    problem: '90일 미구매 고객 37%에게 동일 쿠폰을 보내 클릭률과 브랜드 반응이 낮았습니다.', target: '첫 구매 품목과 마지막 행동이 다른 5개 휴면 고객 세그먼트',
    strategy: '관심 콘텐츠 → 장바구니 리마인드 → 혜택의 3단계 자동화 여정 설계', execution: '이메일 6종·카카오 4종의 제목·혜택·발송 시간 실험과 중복 접촉 제외',
    result: '휴면 재구매율을 4.8%에서 8.1%, 클릭률을 3.6%에서 7.4%로 높였습니다.', insight: '일괄 할인보다 이전 구매 제품의 교체 주기를 알려주는 정보형 메시지가 재구매를 더 만들었습니다.',
    metrics: [{ name: '재구매율', before: '4.8%', value: '8.1%', target: '7%' }, { name: '메시지 클릭률', before: '3.6%', value: '7.4%', target: '6%' }, { name: '자동화 여정', value: '3단계', status: '5개 세그먼트' }, { name: '메시지 소재', value: '10종' }],
    funnel: [{ label: '휴면 대상', value: 18600 }, { label: '메시지 오픈', value: 8220 }, { label: '상품 클릭', value: 1376 }, { label: '재구매', value: 1507 }],
  }),
  '서울 한입 로컬 콘텐츠 채널': marketerArtifact({
    problem: '기존 맛집 콘텐츠는 사진과 별점 중심이라 가게의 취향과 방문 이유가 남지 않았습니다.', target: '동네 산책과 새로운 메뉴 발견을 즐기는 20–30대 직장인',
    strategy: '한 메뉴·만드는 사람·산책 코스의 3개 콘텐츠 기둥과 저장 CTA 포맷 구축', execution: '숏폼 48편의 훅·길이·업로드 시간·내레이션을 한 번에 하나씩 실험',
    result: '팔로워 1.2만, 누적 조회 186만, 평균 저장률 6.8%를 달성했습니다.', insight: '조회수보다 저장률과 프로필 방문률을 기준으로 편성하자 협업 매장 방문 문의로 이어졌습니다.',
    metrics: [{ name: '팔로워', value: '1.2만', target: '1만' }, { name: '누적 조회', value: '186만', target: '150만' }, { name: '평균 저장률', value: '6.8%', target: '5%' }, { name: '브랜드 협업', value: '7건' }],
    funnel: [{ label: '조회', value: 1860000 }, { label: '프로필 방문', value: 82400 }, { label: '저장', value: 126480 }, { label: '팔로우', value: 12000 }],
  }),
  '핀데이 앱 설치 캠페인': marketerArtifact({
    problem: '설치 CPI가 높고 설치 사용자의 절반 이상이 회원가입 중 이탈했습니다.', target: '월급 관리가 처음인 사회초년생 신규 사용자',
    strategy: '설치가 아닌 첫 예산 등록을 핵심 전환으로 정의하고 채널·소재·온보딩을 연결', execution: '3개 메시지 축의 소재 32종과 랜딩 3종을 AppsFlyer·GA4 대시보드로 비교',
    result: 'CPI를 4,120원에서 2,760원으로 낮추고 가입 완료율을 46%에서 61%로 높였습니다.', insight: '싼 설치보다 예산 등록률이 높은 월급 관리 소재에 예산을 옮겨 유효 가입당 비용을 29% 절감했습니다.',
    metrics: [{ name: 'CPI', before: '4,120원', value: '2,760원', target: '3,000원' }, { name: '가입 완료율', before: '46%', value: '61%', target: '58%' }, { name: '유효 가입당 비용', value: '-29%', status: '첫 예산 등록 기준' }, { name: '실험 소재', value: '32종' }],
    funnel: [{ label: '광고 클릭', value: 48200 }, { label: '설치', value: 11700 }, { label: '가입 완료', value: 7137 }, { label: '예산 등록', value: 4280 }],
  }),
  '월요일의 취향 뉴스레터': marketerArtifact({
    problem: '주말 큐레이션은 정보가 많고 길어 바쁜 직장인이 끝까지 읽거나 다시 찾기 어려웠습니다.', target: '월요일 점심 5분 안에 취향을 발견하고 싶은 25–34세 직장인',
    strategy: '하나의 테마·세 개의 추천·한 문장의 질문으로 포맷을 고정하고 관심사별 순서를 개인화', execution: '24회 발행하며 제목·발송 시간·첫 추천 위치와 친구 추천 리워드를 순차 실험',
    result: '구독자 3,420명, 오픈율 47.8%, 클릭률 9.6%, 추천 유입 34%를 만들었습니다.', insight: '한 편의 클릭보다 다음 호 재오픈율이 높은 콘텐츠를 편성한 것이 자발적 추천과 장기 성장을 만들었습니다.',
    metrics: [{ name: '구독자', value: '3,420명', target: '3,000명' }, { name: '오픈율', value: '47.8%', target: '40%' }, { name: '클릭률', value: '9.6%', target: '8%' }, { name: '추천 유입', value: '34%', target: '25%' }],
    funnel: [{ label: '발송', value: 3420 }, { label: '오픈', value: 1635 }, { label: '클릭', value: 328 }, { label: '추천 전환', value: 1163 }],
  }),
};

const EXAMPLE_ARTIFACT_COVERS = {
  '모아 — 취향 기반 모임 탐색 서비스': 'code-diff',
  '페이퍼리스 — 전자계약 대시보드': 'quality-matrix',
  '캠퍼스픽 웹 성능 개선': 'performance-report',
  '오픈UI 접근성 개선 기여': 'accessibility-audit',
  'DevLink — 개발 동아리 운영 플랫폼': 'automation-flow',
  '끼니로그 — 1인 가구 식비 관리': 'product-roadmap',
  '클래스온 수강 이탈 개선': 'experiment-board',
  '우리동네 안심귀가 서비스': 'discovery-map',
  '캠퍼스 셔틀 예약 경험 개선': 'service-blueprint',
  '동네상점 재고관리 운영 정책': 'policy-system',
  '모닝빈 신제품 런칭 캠페인': 'launch-dashboard',
  '제로웨이스트 위크 CRM 캠페인': 'crm-journey',
  '서울 한입 로컬 콘텐츠 채널': 'content-scoreboard',
  '핀데이 앱 설치 캠페인': 'paid-funnel',
  '월요일의 취향 뉴스레터': 'growth-report',
};

const project = ({ title, role, period, tag, description, bullets, skills, keywords, thumbnailUrl, goal, sections, wordmark, stamp }) => {
  const artifact = EXAMPLE_ARTIFACTS[title] || {};
  return ({
  id: title,
  title,
  company: title,
  role,
  period,
  date: period,
  tag,
  description,
  bullets,
  skills,
  keywords,
  thumbnailUrl,
  wordmark,
  stamp,
  jobCategory: artifact.jobCategory,
  structuredResult: {
    ...artifact,
    jobCategory: artifact.jobCategory,
    projectOverview: { duration: period, role, goal, techStack: skills, summary: description },
    exportConfig: {
      jobCategory: artifact.jobCategory,
      jobCoreShowcase: true,
      artifactCover: true,
      artifactCoverVariant: EXAMPLE_ARTIFACT_COVERS[title],
      sections: sections.map(({ title: sectionTitle, content }, index) => ({
        key: `section-${index + 1}`,
        label: sectionTitle,
        title: sectionTitle,
        type: 'custom',
        content,
      })),
    },
  },
  });
};

export const DEVELOPER_EXAMPLE = {
  templateId: 'web-1',
  userName: '김도윤',
  headline: '사용자의 다음 행동을 설계하는 프론트엔드 개발자',
  webIntro: '복잡한 요구사항을 빠르고 안정적인 화면으로 바꿉니다. 기획 의도를 이해하고, 데이터로 개선점을 찾으며, 팀이 오래 관리할 수 있는 코드를 지향합니다.',
  about: '안녕하세요. 프론트엔드 개발자 김도윤입니다. 컴퓨터공학을 전공한 뒤 1년 동안 세 번의 팀 프로젝트와 한 번의 현장실습을 거치며 사용자에게 실제로 닿는 제품을 만들었습니다. 단순히 화면을 구현하는 데서 멈추지 않고 로딩 속도, 접근성, 오류율처럼 사용자가 체감하는 품질을 수치로 확인합니다. 디자이너·백엔드 개발자와 명확하게 소통하고, 작은 개선을 빠르게 배포하는 팀에서 성장하고 싶습니다.',
  location: '서울 · 원격 근무 가능',
  contact: { email: 'doyoon.kim@example.com', phone: '010-2486-7315', website: 'github.com/doyoon-portfolio' },
  education: [
    { name: '한빛대학교', degree: '컴퓨터공학과 학사 · GPA 3.8/4.5', period: '2020.03 — 2026.02' },
    { name: '코드잇 프론트엔드 부트캠프', degree: 'React 심화 과정 · 우수 수료', period: '2025.03 — 2025.08' },
  ],
  experiences: [
    project({
      title: '모아 — 취향 기반 모임 탐색 서비스', role: 'Frontend Lead · 기여도 45%', period: '2025.09 — 2026.01 · 5개월', tag: 'TEAM PRODUCT',
      description: '검색 조건이 복잡해 원하는 모임을 찾기 어렵다는 문제를 해결한 5인 팀 프로젝트입니다. 필터 상태를 URL과 동기화하고 이미지 로딩을 최적화해 검색 이탈률을 18% 낮췄습니다.',
      bullets: ['검색 결과 첫 표시 2.8초 → 1.4초', '필터 사용 후 상세 진입률 22% → 31%', '공통 UI 18종으로 화면 개발 시간 약 30% 절감'],
      skills: ['React', 'TypeScript', 'TanStack Query', 'Zustand', 'Playwright'], keywords: ['검색 UX', '성능 최적화', '디자인 시스템'], thumbnailUrl: '/example-assets/dev-moa.svg',
      goal: '관심사와 일정에 맞는 오프라인 모임을 3분 안에 발견하고 신청하게 만들기',
      sections: [
        { title: '프로젝트 소개', content: '동네 기반 소모임을 탐색하고 참여 신청까지 할 수 있는 반응형 웹 서비스입니다. 프론트엔드 2명, 백엔드 2명, 디자이너 1명이 참여했으며 프론트엔드 리드로 검색·필터·신청 플로우와 배포 환경을 담당했습니다.' },
        { title: '문제 정의', content: '사용성 테스트 8명 중 6명이 필터를 바꿀 때 목록이 초기화되는 점을 불편해했습니다. 3G 환경에서는 카드 이미지 때문에 첫 결과가 평균 2.8초 뒤에 보여 검색을 포기하는 사용자가 많았습니다.' },
        { title: '해결 과정', content: '필터를 URLSearchParams와 동기화하고 서버 상태는 TanStack Query로 분리했습니다. 입력에는 300ms debounce를 적용했습니다. 이미지에는 srcset·WebP·lazy loading을 적용하고 카드 스켈레톤으로 체감 대기 시간을 줄였습니다.' },
        { title: '산출물', content: '검색·필터 정보 구조도, 공통 컴포넌트 18종과 Storybook 가이드, Playwright 핵심 시나리오 12개, Lighthouse 전후 비교 리포트, GitHub Actions 배포 파이프라인을 작성했습니다.' },
        { title: '성과와 회고', content: '테스트 사용자 42명의 행동 로그에서 검색 이탈률이 18% 감소했고 상세 진입률은 22%에서 31%로 올랐습니다. 첫 결과 표시는 1.4초로 단축했습니다. 다음에는 이벤트 스키마를 개발 초기에 합의해 분석 누락을 줄이겠습니다.' },
      ],
    }),
    project({
      title: '페이퍼리스 — 전자계약 대시보드', role: 'Frontend Developer · 개인 프로젝트', period: '2025.06 — 2025.08 · 10주', tag: 'DASHBOARD',
      description: '계약 상태를 한눈에 파악하고 반복 업무를 줄이는 B2B 대시보드입니다. 대용량 테이블 렌더링과 폼 오류 처리에 집중해 1,000건 목록도 안정적으로 탐색하도록 구현했습니다.',
      bullets: ['1,000행 렌더링 1.9초 → 0.6초', '키보드만으로 핵심 업무 수행', '핵심 유틸 테스트 커버리지 86%'],
      skills: ['Next.js', 'TypeScript', 'React Hook Form', 'Zod', 'Vitest'], keywords: ['B2B SaaS', '접근성', '테이블 최적화'], thumbnailUrl: '/example-assets/dev-paperless.svg',
      goal: '계약 담당자가 오늘 처리할 업무와 지연 건을 10초 안에 파악하게 만들기',
      sections: [
        { title: '배경', content: '채용 공고에서 자주 요구되는 복잡한 폼, 권한별 화면, 대용량 테이블 역량을 하나의 제품으로 검증하기 위해 만든 개인 프로젝트입니다. 가상의 법무·인사 담당자 업무를 기준으로 사용자 시나리오를 설계했습니다.' },
        { title: '핵심 구현', content: '서버 컴포넌트에서 초기 데이터를 불러오고 클라이언트에서는 정렬·필터 상태만 관리했습니다. React Hook Form과 Zod로 계약 유형별 조건부 검증을 구성하고 실패 원인을 필드 가까이에 안내했습니다. 테이블은 행 가상화를 적용했습니다.' },
        { title: '품질 관리', content: 'WCAG 체크리스트로 포커스 순서, 명도 대비, 스크린리더 레이블을 점검했습니다. Vitest로 금액·날짜·권한 유틸을 검증하고 Playwright로 계약 생성부터 승인 요청까지 자동화했습니다.' },
        { title: '산출물', content: 'ERD, 권한 매트릭스, 컴포넌트 명세, 폼 오류 메시지 가이드, 테스트 시나리오 21개, 성능 측정 리포트, 운영 README와 배포 체크리스트를 완성했습니다.' },
        { title: '결과', content: '1,000건 기준 렌더링을 1.9초에서 0.6초로 줄였고 Lighthouse 접근성 100점을 달성했습니다. 기능 수보다 오류·빈 상태·권한 예외를 먼저 설계하는 것이 B2B 제품 신뢰도에 중요하다는 점을 배웠습니다.' },
      ],
    }),
    project({
      title: '캠퍼스픽 웹 성능 개선', role: 'Frontend Intern · 4인 스쿼드', period: '2025.01 — 2025.02 · 8주', tag: 'INTERNSHIP',
      description: '대학 생활 정보 서비스의 모바일 홈을 개선한 현장실습 프로젝트입니다. 번들 분석과 이미지 정책 정비로 LCP를 3.6초에서 2.1초로 단축했습니다.',
      bullets: ['모바일 LCP 3.6초 → 2.1초', '초기 JavaScript 번들 31% 감소', '회귀 방지 성능 예산 문서화'],
      skills: ['React', 'JavaScript', 'Vite', 'Sentry', 'Lighthouse CI'], keywords: ['Core Web Vitals', '번들 분석', '모니터링'], thumbnailUrl: '/example-assets/dev-campus.svg',
      goal: '저사양 모바일 환경에서도 홈의 핵심 콘텐츠를 2.5초 안에 보여주기',
      sections: [
        { title: '담당 업무', content: '프론트엔드 인턴으로 홈 화면 성능 진단, 개선안 우선순위화, 이미지 컴포넌트 수정, 배포 후 지표 모니터링을 맡았습니다. 매주 개발자·디자이너와 개선 결과를 공유했습니다.' },
        { title: '진단', content: 'Lighthouse와 Chrome Performance로 히어로 이미지 지연, 사용하지 않는 아이콘 패키지, 초기 진입에 불필요한 모달 코드를 병목으로 확인했습니다.' },
        { title: '실행', content: '이미지를 AVIF/WebP로 제공하고 크기별 srcset을 적용했습니다. 아이콘 import를 개별 경로로 바꾸고 모달을 lazy import했습니다. Lighthouse CI에 LCP 2.5초, 초기 번들 250KB 성능 예산을 추가했습니다.' },
        { title: '산출물', content: '성능 병목 리스트, 영향도·난이도 우선순위표, 이미지 사용 규칙, Lighthouse CI 설정, 배포 전후 대시보드, 팀 공유용 10분 발표 자료를 제작했습니다.' },
        { title: '성과', content: '모바일 LCP가 3.6초에서 2.1초로 줄었고 초기 JavaScript는 31% 감소했습니다. 수치를 근거로 개선 우선순위를 제안하는 법과 기존 코드에 안전하게 변화를 넣는 방식을 익혔습니다.' },
      ],
    }),
    project({
      title: '오픈UI 접근성 개선 기여', role: 'Open-source Contributor · 개인 기여', period: '2024.11 — 2025.02 · 4개월', tag: 'OPEN SOURCE',
      description: '교육용 오픈소스 UI 라이브러리의 키보드 탐색과 스크린리더 문제를 개선했습니다. 이슈 11건을 재현하고 7개 PR을 제출해 핵심 컴포넌트의 접근성 회귀를 줄였습니다.',
      bullets: ['접근성 이슈 11건 분석 · PR 7건 반영', '키보드 핵심 시나리오 오류 14건 → 2건', 'axe 자동 검사와 기여 가이드 추가'],
      skills: ['React', 'Storybook', 'axe-core', 'GitHub Actions'], keywords: ['오픈소스', '웹 접근성', '문서화'],
      goal: '마우스를 사용하기 어려운 학습자도 핵심 UI를 동일하게 조작하도록 만들기',
      sections: [
        { title: '참여 배경', content: '실제 협업 방식과 코드 리뷰를 경험하기 위해 초보 기여자 라벨이 있는 교육용 UI 라이브러리를 선택했습니다. 먼저 기존 이슈와 로드맵을 읽고 유지관리자에게 접근성 점검 범위를 제안했습니다.' },
        { title: '접근성 진단', content: '버튼, 탭, 모달, 드롭다운을 키보드와 NVDA로 점검했습니다. 포커스가 모달 밖으로 빠지는 문제, 방향키 동작 불일치, 상태 변경 안내 누락 등 11건을 재현 절차와 함께 등록했습니다.' },
        { title: '구현과 검증', content: '포커스 트랩과 복귀 로직을 공통 훅으로 분리하고 탭 컴포넌트에 WAI-ARIA 패턴을 적용했습니다. Storybook 상호작용 테스트와 axe 검사를 CI에 추가해 같은 문제가 다시 들어오지 않게 했습니다.' },
        { title: '협업 산출물', content: '재현 가능한 이슈 11건, 코드 PR 7건, 접근성 체크리스트, Storybook 테스트 18개, 초보 기여자를 위한 로컬 테스트 가이드를 작성했습니다. 리뷰 의견은 커밋 단위로 반영하고 변경 이유를 남겼습니다.' },
        { title: '결과와 회고', content: '키보드 핵심 시나리오 오류가 14건에서 2건으로 줄었고 7개 PR이 릴리스에 포함됐습니다. 정답을 먼저 제시하기보다 재현 조건과 영향 범위를 명확히 공유할 때 오픈소스 협업 속도가 빨라진다는 점을 배웠습니다.' },
      ],
    }),
    project({
      title: 'DevLink — 개발 동아리 운영 플랫폼', role: 'Full-stack Developer · 4인 팀', period: '2024.06 — 2024.10 · 5개월', tag: 'SIDE PROJECT',
      description: '출석·스터디 모집·공지 업무가 여러 도구에 흩어진 문제를 해결한 동아리 운영 서비스입니다. 자동 알림과 운영 대시보드로 주간 관리 시간을 3시간에서 50분으로 줄였습니다.',
      bullets: ['운영 업무 주 3시간 → 50분', '행사 노쇼율 23% → 9%', '활성 회원 84명 · 8주 운영'],
      skills: ['Next.js', 'Firebase', 'Cloud Functions', 'Sentry'], keywords: ['운영 자동화', '서버리스', '관측성'],
      goal: '운영진의 반복 업무를 줄이고 회원이 필요한 활동을 한곳에서 찾게 만들기',
      sections: [
        { title: '문제 정의', content: '운영진 5명과 회원 14명을 인터뷰한 결과 출석은 스프레드시트, 모집은 메신저, 공지는 문서 도구에 나뉘어 있었습니다. 신청 누락과 행사 전날 취소가 반복돼 운영 비용이 커지고 있었습니다.' },
        { title: '역할과 설계', content: '회원·운영진 권한 모델, 스터디 모집, QR 출석, 알림 예약 기능을 담당했습니다. Firebase 보안 규칙과 데이터 구조를 먼저 정의하고, 개인정보 보관 기간과 탈퇴 시 삭제 정책을 운영진과 합의했습니다.' },
        { title: '핵심 구현', content: 'Cloud Functions로 행사 하루 전·한 시간 전 알림을 자동 발송하고 QR 토큰에는 만료 시간을 적용했습니다. Sentry 오류 추적과 실패 작업 재시도 큐를 두어 운영자가 알림 누락을 확인할 수 있게 했습니다.' },
        { title: '산출물', content: '업무 흐름도, Firestore 데이터 모델, 권한 매트릭스, 운영 대시보드, 알림 정책표, 장애 대응 문서, 사용자 가이드와 20개 핵심 시나리오 테스트를 완성했습니다.' },
        { title: '운영 성과', content: '활성 회원 84명이 8주 동안 사용했고 행사 노쇼율은 23%에서 9%로 낮아졌습니다. 운영진의 주간 관리 시간도 3시간에서 50분으로 줄었습니다. 출시 이후 문의를 유형화해 빈 상태와 오류 안내를 지속 개선했습니다.' },
      ],
    }),
  ],
  skills: { languages: ['TypeScript', 'JavaScript', 'HTML/CSS'], frameworks: ['React', 'Next.js', 'TanStack Query'], tools: ['Git/GitHub', 'Figma', 'Storybook'], others: ['웹 접근성', '성능 최적화', '테스트 자동화'] },
  skillLevels: { TypeScript: 82, React: 85, 'Next.js': 76, 'Git/GitHub': 84 },
  awards: [
    { date: '2025.12', title: '한빛대학교 SW 캡스톤디자인 우수상' },
    { date: '2025.08', title: '코드잇 프론트엔드 부트캠프 우수 수료' },
    { date: '2025.05', title: '정보처리기사' },
  ],
  webTheme: { bg: '#f4f1ea', ink: '#141414', accent: '#ff4d00' },
  webCopy: { w1Eyebrow: 'Frontend Developer Portfolio', w1Availability: '신입 포지션 지원 중', w1HeaderContact: 'CONTACT', w1WorksLabel: 'SELECTED WORKS', w1ProjectCountLabel: 'CASE STUDIES', w1StatProjects: '프로젝트 · 실무 경험', w1StatAwards: '수상 · 자격', w1StatSkills: '기술 · 협업 역량' },
};

export const PLANNER_EXAMPLE = {
  templateId: 'web-3',
  userName: '박서연',
  headline: '흩어진 목소리에서 다음 제품의 근거를 찾는 서비스 기획자',
  webIntro: '사용자 인터뷰와 행동 데이터를 함께 보며 문제를 정의합니다. 가설을 작은 기능으로 검증하고, 팀이 같은 목표를 보도록 문서와 지표를 설계합니다.',
  about: '안녕하세요. 신입 서비스 기획자 박서연입니다. 경영정보학을 전공하고 1년간 사이드 프로젝트, 기업 연계 프로젝트, 서비스 운영 인턴을 경험했습니다. 모호한 요청을 바로 기능으로 옮기기보다 누구의 어떤 문제가 반복되는지 먼저 확인합니다. 인터뷰·데이터 분석·정책 설계·QA까지 제품이 출시되는 전 과정을 책임감 있게 연결하는 기획자가 되겠습니다.',
  location: '서울 · 수도권',
  contact: { email: 'seoyeon.park@example.com', phone: '010-5731-8426', website: 'notion.site/seoyeon-product' },
  education: [
    { name: '새봄대학교', degree: '경영정보학과 학사 · 데이터사이언스 부전공', period: '2020.03 — 2025.02' },
    { name: 'PM 부트캠프 12기', degree: '서비스 기획·데이터 분석 과정', period: '2025.03 — 2025.06' },
  ],
  experiences: [
    project({
      title: '끼니로그 — 1인 가구 식비 관리', role: 'Product Manager · 6인 팀', period: '2025.08 — 2026.01 · 6개월', tag: 'MVP',
      description: '영수증 기록이 번거로워 가계부를 포기하는 1인 가구를 위해 사진 한 장으로 식비를 기록하는 MVP를 기획했습니다. 4주 리텐션 27%와 기록 완료율 71%를 확인했습니다.',
      bullets: ['인터뷰 15명·설문 126명으로 문제 정의', '기록 완료율 71% · 4주 리텐션 27%', 'OCR 실패 복구 정책으로 이탈 16%p 개선'],
      skills: ['Figma', 'Notion', 'Amplitude', 'SQL', 'Jira'], keywords: ['MVP', '사용자 인터뷰', '리텐션'], thumbnailUrl: '/example-assets/pm-meallog.svg',
      goal: '영수증 촬영 후 30초 안에 식비 기록을 완료하게 만들기',
      sections: [
        { title: '문제 발견', content: '1인 가구 15명 인터뷰에서 11명이 식비를 줄이고 싶지만 품목을 직접 입력하는 과정 때문에 가계부를 2주 안에 포기했습니다. 기존 서비스 리뷰 240건을 분류해 입력 피로와 외식·장보기 구분의 어려움을 핵심 문제로 정했습니다.' },
        { title: '가설과 MVP', content: '영수증 사진에서 날짜·금액·상호를 자동 추출하고 사용자는 식사 유형만 고르면 기록 부담이 줄어들 것이라 가정했습니다. 우선순위 매트릭스로 통계·챌린지를 제외하고 촬영, 검수, 주간 요약에 집중했습니다.' },
        { title: '정책과 협업', content: 'OCR 신뢰도에 따라 자동 확정·사용자 확인·직접 입력으로 나누는 예외 정책을 설계했습니다. PRD, 화면 흐름, 이벤트 택소노미, API 요구사항을 작성하고 주 2회 스프린트 리뷰로 범위를 조정했습니다.' },
        { title: '산출물', content: '리서치 리포트, 문제정의서, 경쟁 서비스 벤치마크, MVP 우선순위표, PRD 24쪽, 와이어프레임 32화면, OCR 예외 정책표, Amplitude 이벤트 명세, QA 테스트케이스 86개를 제작했습니다.' },
        { title: '성과와 다음 실험', content: '테스트 사용자 48명 기준 기록 완료율 71%, 4주 리텐션 27%를 기록했습니다. OCR 실패 안내를 수정해 해당 단계 이탈을 34%에서 18%로 낮췄습니다. 다음 실험은 주간 요약 알림이 재방문에 미치는 영향입니다.' },
      ],
    }),
    project({
      title: '클래스온 수강 이탈 개선', role: '서비스 기획 인턴 · Growth Squad', period: '2025.06 — 2025.08 · 12주', tag: 'GROWTH',
      description: '온라인 클래스의 첫 강의 전 이탈 원인을 분석하고 온보딩 체크리스트를 기획했습니다. A/B 테스트에서 첫 강의 시작률을 54%에서 66%로 개선했습니다.',
      bullets: ['퍼널·VOC 312건으로 병목 정의', '첫 강의 시작률 12%p 상승', '개발 범위를 2주 MVP로 축소'],
      skills: ['GA4', 'BigQuery', 'Looker Studio', 'Figma', 'Confluence'], keywords: ['퍼널 분석', 'A/B 테스트', '온보딩'], thumbnailUrl: '/example-assets/pm-classon.svg',
      goal: '결제 후 24시간 안에 첫 강의를 시작하는 사용자의 비율 높이기',
      sections: [
        { title: '상황', content: '결제 전환은 안정적이었지만 신규 수강생의 46%가 결제 후 24시간 안에 강의를 시작하지 않았습니다. 첫 강의를 시작한 집단의 4주 완강률이 2.3배 높아 초기 행동을 개선 과제로 선정했습니다.' },
        { title: '분석', content: 'GA4 퍼널을 기기·유입 채널·상품 유형별로 분해하고 VOC 312건을 태깅했습니다. 모바일에서 학습 페이지 진입 경로가 숨겨져 있고 준비물 안내를 찾기 어려운 점이 주요 원인이었습니다.' },
        { title: '기획', content: '결제 완료 화면에 3단계 시작 체크리스트와 바로 학습하기 CTA를 배치했습니다. 전면 재설계 대신 2주 내 검증 가능한 범위로 줄여 가설, 타깃, 성공·가드레일 지표를 정의했습니다.' },
        { title: '산출물', content: '퍼널 분석 대시보드, VOC 어피니티맵, 개선안 우선순위표, A/B 테스트 기획서, 화면·상태 정책, 이벤트 명세 14개, QA 체크리스트와 결과 공유 문서를 작성했습니다.' },
        { title: '결과', content: '2주간 신규 결제자 1,842명을 대상으로 한 테스트에서 첫 강의 시작률이 54%에서 66%로 12%p 상승했고 환불률은 유의미하게 증가하지 않았습니다. 실험 종료 후 전체 사용자에게 적용했습니다.' },
      ],
    }),
    project({
      title: '우리동네 안심귀가 서비스', role: 'Product Planner · 기업 연계', period: '2025.03 — 2025.05 · 10주', tag: 'DISCOVERY',
      description: '야간 귀가자의 불안을 줄이는 지역 기반 안전 서비스 콘셉트를 제안했습니다. 현장 조사와 인터뷰로 안전 점수·지인 공유 기능의 프로토타입을 검증했습니다.',
      bullets: ['심층 인터뷰 12명·현장 관찰 3회', '과업 성공률 58% → 87%', '협력사 최종 발표 우수팀'],
      skills: ['Figma', 'Maze', 'Miro', 'Google Sheets'], keywords: ['서비스 디스커버리', '프로토타입', '사용성 테스트'], thumbnailUrl: '/example-assets/pm-safehome.svg',
      goal: '20대 여성 사용자가 늦은 귀가 경로를 안심하고 선택하도록 돕기',
      sections: [
        { title: '리서치', content: '야간 이동 경험이 있는 20대 여성 12명을 인터뷰하고 대학가·역세권에서 3회 현장 관찰을 진행했습니다. 밝은 큰길을 선호하지만 기존 지도는 최단 시간 중심이라 매번 CCTV와 편의점을 따로 확인한다는 행동을 발견했습니다.' },
        { title: '서비스 정의', content: '가로등·CCTV·24시간 매장·유동 인구를 조합한 안심 점수를 제공하고, 선택 경로와 도착 예정 시간을 지인에게 공유하는 콘셉트를 정의했습니다. 데이터 확보 가능성과 개인정보 위험도 함께 검토했습니다.' },
        { title: '검증', content: '저충실도 테스트에서 점수 의미를 이해하지 못하는 문제가 있어 숫자 대신 안전 요소별 근거를 펼쳐 보이게 했습니다. 2차 고충실도 테스트에서 경로 선택 과업 성공률이 58%에서 87%로 올랐습니다.' },
        { title: '산출물', content: '리서치 계획서, 인터뷰 녹취·어피니티맵, 퍼소나와 여정지도, 서비스 블루프린트, 데이터 요구사항, 와이어프레임 28화면, Maze 테스트 리포트, 15장 제안서를 완성했습니다.' },
        { title: '배운 점', content: '좋은 아이디어보다 데이터 출처와 운영 주체를 구체화해야 서비스가 현실성을 얻는다는 점을 배웠습니다. 협력사 피드백을 반영해 신고 정보의 신뢰도와 갱신 주기를 후속 과제로 제시했습니다.' },
      ],
    }),
    project({
      title: '캠퍼스 셔틀 예약 경험 개선', role: 'Product Analyst · 4인 팀', period: '2024.11 — 2025.02 · 12주', tag: 'UX IMPROVEMENT',
      description: '좌석 선택과 탑승 확인이 복잡한 교내 셔틀 예약 과정을 개선했습니다. 로그와 현장 관찰을 바탕으로 예약 완료율을 63%에서 81%로 높이는 안을 검증했습니다.',
      bullets: ['예약 퍼널 8,420건 분석', '예약 완료율 63% → 81%', '현장 문의 1일 26건 → 11건'],
      skills: ['GA4', 'SQL', 'Figma', 'Maze'], keywords: ['퍼널 개선', '현장 관찰', '정책 설계'],
      goal: '처음 이용하는 학생도 1분 안에 셔틀 좌석을 예약하고 탑승 방법을 이해하게 만들기',
      sections: [
        { title: '문제 탐색', content: '한 학기 예약 로그 8,420건을 분석하니 좌석 선택 후 탑승 장소 확인 단계에서 이탈이 집중됐습니다. 정류장 현장 관찰 4회와 문의 기록 186건을 통해 노선 이름과 실제 표지판 표현이 다르다는 점도 확인했습니다.' },
        { title: '가설 수립', content: '노선을 시간 중심으로 먼저 고르게 하고 좌석 선택을 다음 단계로 분리하면 인지 부담이 줄 것이라 가정했습니다. 정류장 사진과 지도 랜드마크를 함께 제공하고 예약 완료 화면에 QR 탑승 방법을 바로 노출했습니다.' },
        { title: '정책 설계', content: '출발 10분 전 취소, 대기 순번 자동 승급, QR 캡처 방지, 지각 탑승 처리까지 17개 예외 상황을 정의했습니다. 운영팀과 기사 관점의 상태를 별도로 정리해 화면 문구와 관리자 처리를 연결했습니다.' },
        { title: '산출물', content: '퍼널 분석 리포트, 현장 관찰 기록, 사용자 흐름도, 상태·예외 정책표, 와이어프레임 21화면, 운영자 화면 명세, Maze 사용성 테스트 결과와 개선 우선순위표를 제작했습니다.' },
        { title: '검증 결과', content: '학생 32명 대상 프로토타입 테스트에서 예약 완료율이 63%에서 81%로 높아졌고 평균 소요 시간은 2분 14초에서 58초로 줄었습니다. 시범 운영 후 현장 문의도 하루 26건에서 11건으로 감소했습니다.' },
      ],
    }),
    project({
      title: '동네상점 재고관리 운영 정책', role: 'Service Operations Intern · PO 협업', period: '2024.07 — 2024.10 · 14주', tag: 'OPERATIONS',
      description: '소상공인 재고관리 서비스의 반복 문의와 재고 불일치 문제를 운영 정책으로 정리했습니다. 문의 유형을 제품 개선으로 연결해 재고 불일치 신고율을 18%에서 7%로 낮췄습니다.',
      bullets: ['고객 문의 684건 분류·원인 분석', '재고 불일치 신고율 18% → 7%', '평균 첫 응답 9.4시간 → 3.1시간'],
      skills: ['Zendesk', 'Notion', 'SQL', 'Looker Studio'], keywords: ['서비스 운영', 'VOC 분석', '어드민 정책'],
      goal: '상점주가 재고 오류를 스스로 해결하고 운영팀은 반복 문의 대신 고위험 문제에 집중하게 만들기',
      sections: [
        { title: '운영 현황', content: '3개월간 접수된 문의 684건을 태깅하니 입고 취소, 단위 변환, 동시 수정에서 재고 불일치가 반복됐습니다. 답변 템플릿과 담당 기준이 없어 같은 질문에도 처리 방식과 소요 시간이 달랐습니다.' },
        { title: '원인 분석', content: '문의 데이터와 행동 로그를 연결해 사용자의 마지막 행동을 확인했습니다. 단순 사용법 문의와 데이터 복구가 필요한 장애를 구분하고, 빈도·매출 영향·복구 난이도로 개선 우선순위를 정했습니다.' },
        { title: '정책 개선', content: '입고 취소 시 재고 복원 규칙, 여러 기기에서 수정할 때의 충돌 안내, 관리자 보정 권한과 이력 보관 기준을 정의했습니다. 자주 묻는 문제는 제품 안의 도움말과 셀프 진단 흐름으로 전환했습니다.' },
        { title: '산출물', content: 'VOC 분류 체계, 주간 운영 대시보드, 23개 응대 매크로, 재고 보정 정책서, 관리자 기능 요구사항, 장애 에스컬레이션 기준, 도움말 문서 14편과 월간 개선 리포트를 작성했습니다.' },
        { title: '성과와 학습', content: '재고 불일치 신고율이 18%에서 7%로 줄었고 첫 응답 시간은 9.4시간에서 3.1시간으로 단축됐습니다. 운영 데이터가 단순 민원 기록이 아니라 제품의 예외 상태를 발견하는 가장 가까운 근거라는 점을 배웠습니다.' },
      ],
    }),
  ],
  skills: { tools: ['Figma', 'Notion', 'Jira', 'Amplitude'], languages: ['SQL', 'GA4', 'BigQuery'], frameworks: ['PRD', 'A/B Test', 'Scrum'], others: ['사용자 인터뷰', '정책 설계', 'QA'] },
  skillLevels: { Figma: 86, SQL: 74, Amplitude: 78, '사용자 인터뷰': 88 },
  awards: [
    { date: '2025.12', title: '제4회 대학생 프로덕트 챌린지 최우수상' },
    { date: '2025.05', title: '새봄대학교 기업 연계 프로젝트 우수팀' },
    { date: '2025.02', title: 'SQLD 데이터분석 준전문가' },
  ],
  webTheme: { bg: '#f7f5f0', ink: '#111111', accent: '#c8ff2f' },
  webCopy: { w3BrandTop: 'PRODUCT', w3BrandBottom: 'FINDER', w3HeroAside: '사용자 문제와 비즈니스 기회 사이에서 실행 가능한 답을 찾습니다.', w3HeroLine1: 'FIND', w3HeroLine2: 'THE REAL', w3HeroLine3: 'PROBLEM', w3ProjectsLabel: 'CASE STUDIES', w3ProjectItemLabel: 'CASE', w3FilterProjects: '케이스 스터디', w3FilterSkills: '기획 도구', w3FilterAwards: '수상·자격', w3FilterStatus: '지원 상태', w3ExperienceLabel: 'PROJECT LOG', w3SkillsLabel: 'PLANNING TOOLKIT' },
};

export const MARKETER_EXAMPLE = {
  templateId: 'web-4',
  userName: '이수민',
  headline: '콘텐츠의 반응을 매출의 이유로 연결하는 주니어 마케터',
  webIntro: '고객이 멈춰 보는 한 문장을 만들고, 클릭 이후의 숫자까지 추적합니다. 작은 예산도 가설과 소재 단위로 나누어 다음 캠페인의 근거를 남깁니다.',
  about: '안녕하세요. 콘텐츠와 퍼포먼스를 함께 보는 신입 마케터 이수민입니다. 광고홍보학을 전공하고 1년 동안 브랜드 인턴, 교내 프로젝트, 개인 채널 운영을 통해 기획부터 제작·집행·분석까지 직접 경험했습니다. 조회수 하나보다 어떤 고객이 왜 반응했고 다음 행동으로 이어졌는지를 설명할 수 있는 마케터를 목표로 합니다. 브랜드의 말투를 지키면서도 성과를 만드는 실험을 꾸준히 제안하겠습니다.',
  location: '서울 · 경기',
  profileImageUrl: '/example-assets/mkt-profile.svg',
  contact: { email: 'sumin.lee@example.com', phone: '010-6194-2873', website: 'sumin-marketing.notion.site', instagram: '@sumin.marketing.lab' },
  education: [
    { name: '가온대학교', degree: '광고홍보학과 학사 · 소비자학 복수전공', period: '2020.03 — 2025.02' },
    { name: '데이터 마케팅 실무 과정', degree: 'GA4·Meta Ads·CRM 프로젝트 수료', period: '2025.03 — 2025.05' },
  ],
  experiences: [
    project({
      title: '모닝빈 신제품 런칭 캠페인', role: 'Marketing Intern · 캠페인 오너', period: '2025.09 — 2025.12 · 4개월', tag: 'Launch',
      description: '저당 그래놀라 신제품의 타깃과 메시지를 재정의하고 Meta 광고·크리에이터 시딩을 운영했습니다. 1,200만원 예산으로 첫 달 매출 4,860만원과 ROAS 405%를 달성했습니다.',
      bullets: ['런칭 첫 달 매출 4,860만원 · ROAS 405%', '소재 24종·메시지 6개 A/B 테스트', '신규 고객 68% · 랜딩 CVR 3.1%'],
      skills: ['Meta Ads', 'GA4', 'Google Sheets', 'Figma', 'Slack'], keywords: ['신제품 런칭', '퍼포먼스 광고', '크리에이터 시딩'], thumbnailUrl: '/example-assets/mkt-morningbean.svg',
      goal: '저당 간식을 찾는 25–34세 직장인에게 신제품을 알리고 첫 구매 만들기', wordmark: 'Morning', stamp: '🥣',
      sections: [
        { title: '문제와 목표', content: '브랜드 인지도는 있었지만 기존 고객이 40대에 집중돼 신제품 핵심 타깃인 25–34세 유입이 부족했습니다. 런칭 4주 내 매출 3,500만원, ROAS 300%, 신규 고객 비중 55%를 목표로 설정했습니다.' },
        { title: '타깃 인사이트', content: '리뷰 518건과 자사몰 검색어를 분석해 젊은 고객이 단순 저칼로리보다 출근 전 간편함과 포만감을 함께 원한다는 점을 찾았습니다. 메시지를 칼로리 강조에서 바쁜 아침을 위한 든든한 3분으로 전환했습니다.' },
        { title: '실행', content: '문제·제품·후기형 3개 크리에이티브 축에서 24종 소재를 제작하고 6개 메시지를 A/B 테스트했습니다. 후기형을 확대하고 랜딩 상단에 영양 성분 비교와 첫 구매 혜택을 배치했습니다. 마이크로 크리에이터 18명에게 시딩했습니다.' },
        { title: '산출물', content: '캠페인 브리프, 타깃 페르소나, 메시지 하우스, 4주 콘텐츠 캘린더, 광고 소재 24종, 크리에이터 가이드, UTM 규칙표, 일간 성과 대시보드, 주차별 회고 리포트를 제작했습니다.' },
        { title: '성과와 인사이트', content: '첫 달 매출 4,860만원, ROAS 405%, 신규 고객 비중 68%를 기록했습니다. 후기형 세로 영상이 정적 이미지보다 CPA가 31% 낮았습니다. 할인보다 사용 장면을 먼저 보여줄 때 유입 품질이 높아진다는 후속 가설을 얻었습니다.' },
      ],
    }),
    project({
      title: '제로웨이스트 위크 CRM 캠페인', role: 'CRM Marketer · 팀 프로젝트', period: '2025.06 — 2025.08 · 8주', tag: 'CRM',
      description: '휴면 고객을 행동 기준으로 나누고 이메일·카카오 메시지를 개인화한 리텐션 캠페인입니다. 휴면 고객 재구매율을 4.8%에서 8.1%로 높였습니다.',
      bullets: ['휴면 재구매율 4.8% → 8.1%', '메시지 클릭률 3.6% → 7.4%', '5개 세그먼트·3단계 자동화'],
      skills: ['Braze', 'GA4', 'SQL', 'Google Sheets', 'Canva'], keywords: ['CRM', '세그먼테이션', '리텐션'], thumbnailUrl: '/example-assets/mkt-zeroweek.svg',
      goal: '최근 90일 미구매 고객의 재방문과 두 번째 구매를 만들기', wordmark: 'ZeroWeek', stamp: '🌿',
      sections: [
        { title: '상황', content: '친환경 생활용품몰의 신규 가입자는 늘었지만 최근 90일 미구매 고객이 전체의 37%였습니다. 기존에는 모든 휴면 고객에게 같은 15% 쿠폰을 보내 브랜드 피로도와 낮은 클릭률 문제가 있었습니다.' },
        { title: '전략', content: '첫 구매 품목, 평균 객단가, 마지막 방문 행동을 기준으로 고객을 5개 그룹으로 나눴습니다. 관심 카테고리 콘텐츠, 장바구니 리마인드, 혜택 메시지의 3단계 시나리오를 구성하고 각 단계 중단 조건을 정했습니다.' },
        { title: '실행', content: '제목·혜택·발송 시간을 나눈 테스트를 설계했습니다. 이메일 클릭 사용자는 카카오 혜택 발송에서 제외해 중복 접촉을 줄였고, 상품 추천은 최근 구매 품목과 보완 관계가 있는 카테고리로 개인화했습니다.' },
        { title: '산출물', content: '고객 세그먼트 정의서, SQL 추출 조건, CRM 여정 맵, 이메일 6종·카카오 메시지 4종, 자동화 분기표, 실험 설계서, 코호트 성과 대시보드와 최종 회고 문서를 만들었습니다.' },
        { title: '결과', content: '8주 후 휴면 고객 재구매율은 4.8%에서 8.1%로, 메시지 클릭률은 3.6%에서 7.4%로 상승했습니다. 가장 좋은 반응은 할인형이 아니라 이전 구매 제품의 교체 주기를 알려준 정보형 메시지에서 나왔습니다.' },
      ],
    }),
    project({
      title: '서울 한입 로컬 콘텐츠 채널', role: 'Content Marketer · 개인 채널', period: '2025.02 — 2026.01 · 12개월', tag: 'Content',
      description: '동네 가게의 메뉴와 사람을 소개하는 숏폼 채널을 0부터 운영했습니다. 48편을 발행해 팔로워 1.2만 명, 누적 조회수 186만 회, 평균 저장률 6.8%를 만들었습니다.',
      bullets: ['12개월간 숏폼 48편 발행', '팔로워 1.2만 · 누적 조회 186만', '협업 7건 · 평균 저장률 6.8%'],
      skills: ['Instagram', 'Premiere Pro', 'Photoshop', 'Notion', 'GA4'], keywords: ['숏폼', '콘텐츠 전략', '채널 운영'], thumbnailUrl: '/example-assets/mkt-seoulbite.svg',
      goal: '광고비 없이 동네 가게의 매력을 저장하고 방문하고 싶은 콘텐츠로 전달하기', wordmark: 'SeoulBite', stamp: '🍜',
      sections: [
        { title: '채널 기획', content: '맛집 정보가 메뉴 사진과 별점에 집중돼 가게의 취향과 이야기가 보이지 않는다고 느꼈습니다. 20–30대 직장인을 대상으로 한 메뉴, 만드는 사람, 동네 산책 코스의 3개 콘텐츠 기둥을 정했습니다.' },
        { title: '제작 시스템', content: '아이템 발굴부터 섭외, 촬영, 편집, 성과 기록까지 주 1편 제작 루틴을 만들었습니다. 첫 2초 훅, 메뉴 디테일, 가격·위치 정보, 저장 CTA 순서로 포맷을 표준화하고 매월 상·하위 콘텐츠를 비교했습니다.' },
        { title: '성장 실험', content: '썸네일 문구, 영상 길이, 업로드 시간, 내레이션 유무를 한 번에 하나씩 바꿨습니다. 조회수보다 저장률과 프로필 방문률을 핵심 지표로 보고, 저장률이 높은 산책 코스 결합형 비중을 확대했습니다.' },
        { title: '산출물', content: '채널 콘셉트북, 톤앤매너 가이드, 월간 캘린더, 섭외 메일 템플릿, 촬영 체크리스트, 숏폼 48편, 썸네일 템플릿 6종, 월간 인사이트 리포트 10회, 협업 보고서 7건을 제작했습니다.' },
        { title: '성과와 배운 점', content: '팔로워 1.2만 명, 누적 조회수 186만 회, 평균 저장률 6.8%를 달성했습니다. 협업 매장 7곳 중 5곳이 게시 후 일주일간 방문 문의 증가를 확인했습니다. 꾸준한 포맷과 명확한 편집 기준이 재현 가능한 성장을 만든다는 점을 배웠습니다.' },
      ],
    }),
    project({
      title: '핀데이 앱 설치 캠페인', role: 'Performance Marketer · 3인 팀', period: '2024.10 — 2025.01 · 12주', tag: 'Paid Growth',
      description: '사회초년생 예산관리 앱의 설치 광고와 온보딩 메시지를 함께 개선했습니다. 채널·소재·가입 퍼널을 연결해 CPI를 4,120원에서 2,760원으로 낮췄습니다.',
      bullets: ['CPI 4,120원 → 2,760원', '가입 완료율 46% → 61%', '광고 소재 32종·랜딩 3종 실험'],
      skills: ['Google Ads', 'Meta Ads', 'AppsFlyer', 'GA4'], keywords: ['앱 마케팅', '어트리뷰션', '퍼널 최적화'],
      goal: '설치 수가 아니라 첫 예산 등록까지 완료하는 신규 사용자를 효율적으로 확보하기', wordmark: 'FinDay', stamp: '📊',
      sections: [
        { title: '과제 정의', content: '설치 캠페인의 CPI는 목표보다 38% 높았고 설치 사용자의 절반 이상이 회원가입 중 이탈했습니다. 매체 숫자만 최적화하지 않기 위해 첫 예산 등록을 핵심 전환으로 정하고 채널별 후속 행동을 연결했습니다.' },
        { title: '데이터 정비', content: 'AppsFlyer와 GA4 이벤트 이름, 어트리뷰션 기간, UTM 규칙을 통일했습니다. 채널·소재별 설치, 가입, 예산 등록까지 한 화면에서 보는 대시보드를 만들고 중복 전환과 사내 테스트 기기를 제외했습니다.' },
        { title: '실험 실행', content: '절약 불안, 월급 관리, 소비 리포트의 3개 메시지 축으로 소재 32종을 제작했습니다. 반응이 좋은 월급 관리 메시지를 랜딩과 온보딩 첫 화면까지 이어주고, 가입 단계의 불필요한 선택 항목을 후순위로 제안했습니다.' },
        { title: '산출물', content: '캠페인 브리프, 채널별 예산안, 이벤트·UTM 명세, 소재 32종, 랜딩 3종, 주간 성과 대시보드, 실험 로그, 소재 교체 기준과 최종 인사이트 리포트를 제작했습니다.' },
        { title: '성과', content: '12주 동안 CPI는 4,120원에서 2,760원으로 33% 낮아졌고 가입 완료율은 46%에서 61%로 상승했습니다. 설치가 저렴한 소재보다 첫 예산 등록률이 높은 소재에 예산을 옮겨 유효 가입당 비용도 29% 절감했습니다.' },
      ],
    }),
    project({
      title: '월요일의 취향 뉴스레터', role: 'CRM & Content Marketer · 개인 프로젝트', period: '2024.04 — 2024.12 · 9개월', tag: 'Newsletter',
      description: '직장인의 월요일을 가볍게 만드는 전시·음악·공간 큐레이션 뉴스레터입니다. 24회를 발행해 구독자 3,420명과 평균 오픈율 47.8%를 만들었습니다.',
      bullets: ['뉴스레터 24회 · 구독자 3,420명', '평균 오픈율 47.8% · 클릭률 9.6%', '추천 유입 비중 34%'],
      skills: ['Stibee', 'GA4', 'Notion', 'Photoshop'], keywords: ['뉴스레터', '오디언스 성장', '리퍼럴'],
      goal: '바쁜 직장인이 5분 안에 이번 주 취향 한 가지를 발견하고 저장하게 만들기', wordmark: 'Monday Taste', stamp: '💌',
      sections: [
        { title: '콘셉트 설계', content: '정보가 많은 주말보다 월요일 점심에 짧게 읽을 큐레이션이 필요하다는 가설로 시작했습니다. 25–34세 직장인을 대상으로 매주 하나의 테마, 세 개의 추천, 한 문장의 질문으로 포맷을 고정했습니다.' },
        { title: '초기 독자 확보', content: '관심사 커뮤니티 6곳에서 샘플 호를 공유하고 구독 이유를 묻는 웰컴 설문을 운영했습니다. 응답을 전시, 음악, 공간 세그먼트로 나눠 첫 4주 추천 순서와 제목 문구를 개인화했습니다.' },
        { title: '성장 실험', content: '제목 길이, 발송 시간, 첫 추천 위치를 매회 하나씩 테스트했습니다. 8호부터 친구 추천 링크와 추천 횟수별 리워드를 도입하고, 클릭보다 다음 호 재오픈율이 높은 콘텐츠 유형을 편성에 반영했습니다.' },
        { title: '산출물', content: '브랜드 콘셉트북, 편집 가이드, 뉴스레터 24회, 웰컴 메일 3종, 추천 프로그램 랜딩, 구독 설문, 콘텐츠 성과 대시보드, 월간 회고 8회와 광고 제안서를 제작했습니다.' },
        { title: '성과와 회고', content: '9개월 만에 구독자 3,420명, 평균 오픈율 47.8%, 클릭률 9.6%를 기록했고 신규 구독의 34%가 독자 추천에서 발생했습니다. 콘텐츠 한 편의 성과보다 다시 열어보는 습관과 자발적 추천을 만드는 일관성이 중요했습니다.' },
      ],
    }),
  ],
  skills: { tools: ['GA4', 'Meta Ads', 'Braze', 'Figma'], languages: ['SQL', 'Google Sheets', 'Looker Studio'], frameworks: ['A/B Test', 'CRM Journey', 'Content Calendar'], others: ['카피라이팅', '숏폼 제작', '성과 분석'] },
  skillLevels: { GA4: 82, 'Meta Ads': 80, SQL: 70, 카피라이팅: 86 },
  awards: [
    { date: '2025.11', title: '대학생 디지털 마케팅 공모전 우수상' },
    { date: '2025.05', title: 'GA4 Skillshop Certification' },
    { date: '2025.04', title: '검색광고마케터 1급' },
  ],
  webTheme: { bg: '#fffdf8', ink: '#202020', accent: '#e94e35' },
  webCopy: { w4TopTags: 'CONTENT · PERFORMANCE · CRM', w4HeroWordmark: 'Sumin', w4CoverLabel: 'MARKETING PORTFOLIO', w4AboutLabel: 'ABOUT THE MARKETER', w4KeywordLabel: 'MARKETING KEYWORD', w4ResumeLabel: 'EXPERIENCE & SKILLS', w4ExperienceLabel: 'CAMPAIGN EXPERIENCE', w4CertificateLabel: 'AWARDS & CERTIFICATE', w4ContentsWordmark: 'Campaigns', w4FromValue: 'Customer Insight', w4FooterCopy: 'THANK YOU · LET\'S MAKE THE NEXT GROWTH' },
};

export const PORTFOLIO_EXAMPLES = {
  example1: DEVELOPER_EXAMPLE,
  example2: PLANNER_EXAMPLE,
  example3: MARKETER_EXAMPLE,
};
